from __future__ import annotations

import hashlib
import json
from typing import Final

GRUPOS_EDAFOLOGICOS: Final[dict[str, str]] = {
    "AC": "Acrisol ",
    "AL": "Alisol",
    "AN": "Andosol",
    "AR": "Arenosol",
    "CH": "Chernozem",
    "CL": "Calcisol",
    "CM": "Cambisol",
    "DU": "Durisol",
    "FL": "Fluvisol",
    "GL": "Gleysol",
    "KS": "Kastanozem",
    "LP": "Leptosol",
    "LV": "Luvisol",
    "LX": "Lixisol",
    "NT": "Nitisol",
    "PH": "Phaeozem",
    "PL": "Planosol",
    "RG": "Regosol",
    "SA": "Cuerpo de agua",
    "SC": "Solonchak",
    "SN": "Solonetz",
    "TC": "Technosol",
    "UM": "Umbrisol",
    "VR": "Vertisol",
}

CALIFICADORES_PRIMARIOS_EDAFOLOGICOS: Final[dict[str, str]] = {
    "N/A": "No aplicable ",
    "ab": "Álbico",
    "al": "Álico",
    "an": "Ándico",
    "ap": "Abrúptico",
    "ca": "Calcárico",
    "can": "Endocalcárico",
    "cc": "Cálcico",
    "cm": "Cámbico",
    "cr": "Crómico",
    "dy": "Dístrico",
    "ek": "Ecránico",
    "eu": "Éutrico",
    "fe": "Ferrítico ",
    "fr": "Ferrico ",
    "fv": "Flúvico",
    "gl": "Gléyico",
    "gm": "Grumico ",
    "gr": "Gerico ",
    "ha": "Haplico ",
    "hu": "Húmico",
    "je": "Hiperéutrico",
    "jk": "Hiperesquelético",
    "kk": "Acroesquelético",
    "len": "Endoléptico",
    "lep": "Epiléptico",
    "li": "Lítico",
    "ll": "Lamélico",
    "lo": "Loámico",
    "lv": "Lúvico",
    "lx": "Líxico",
    "mo": "Mólico",
    "ms": "Mesotrófico",
    "mz": "Mázico",
    "ok": "Ortoesquelético",
    "pdn": "Endopetrodúrico",
    "pdp": "Epipetrodúrico",
    "pe": "Pélico",
    "pf": "Plintico",
    "pr": "Prótico",
    "ptn": "Endopétrico",
    "ptp": "Epipétrico",
    "qs": "Glósico",
    "qv": "Gleyico",
    "ro": "Ródico",
    "rz": "Réndzico",
    "si": "Somérico",
    "sk": "Esqueletico",
    "skn": "Endoesquelético",
    "skp": "Epiesquelético",
    "sm": "Somerimólico",
    "sn": "Silándico",
    "so": "Sódico",
    "sp": "Spólico",
    "sq": "Subacuático",
    "st": "Stágnico",
    "sw": "Someriúmbrico",
    "tf": "Téfrico",
    "ub": "Úrbico",
    "um": "Úmbrico",
    "vi": "Vítrico",
    "vr": "Vértico",
    "wc": "Hipocálcico",
}

CALIFICADORES_SECUNDARIOS_EDAFOLOGICOS: Final[dict[str, str]] = {
    "N": "No aplica",
    "N/A": "No aplica",
    "ab": "Álbico",
    "ad": "Arídico",
    "ai": "Árico",
    "al": "Álico",
    "an": "Ándico",
    "ap": "Abrúptico",
    "ar": "Arénico",
    "are": "Pantoarénico",
    "ca": "Calcárico",
    "can": "Endocalcárico",
    "cc": "Cálcico",
    "ccn": "Endocálcico",
    "ce": "Cláyico",
    "cea": "Amphicláyico",
    "cee": "Pantoclático",
    "cm": "Cámbico",
    "cr": "Crómico",
    "ct": "Cutánico",
    "cu": "Colúmnico",
    "dy": "Dístrico",
    "dyp": "Epidístrico",
    "eu": "Éutrico",
    "fr": "Férrico",
    "fv": "Flúvico",
    "gl": "Gléyico",
    "gm": "Grúmico",
    "gz": "Greyzemico",
    "ha": "Háplico",
    "hu": "Húmico",
    "jd": "Hiperdístrico",
    "je": "Hiperéutrico",
    "jh": "Hiperhúmico",
    "kk": "Acroesquelético",
    "len": "Endoléptico",
    "lep": "Epiléptico",
    "ll": "Lamélico",
    "lo": "Loámico",
    "lv": "Lúvico",
    "lx": "Líxico",
    "mf": "Manganiférrico",
    "mo": "Mólico",
    "mz": "Mázico",
    "oh": "Ócrico",
    "ok": "Ortoesquelético",
    "pdn": "Endopetrodúrico",
    "pdp": "Epipetrodúrico",
    "pe": "Pélico",
    "pf": "Plintico",
    "ph": "Páquico",
    "pr": "Prótico",
    "qs": "Glósico",
    "qv": "Gleyico",
    "qz": "Greyzemico",
    "ro": "Ródico",
    "rz": "Réndzico",
    "sk": "Esqueletico",
    "skn": "Endoesquelético",
    "skp": "Epiesquelético",
    "sl": "Síltico",
    "sla": "Salico",
    "sm": "Somerimólico",
    "so": "Sódico",
    "son": "Endosódico",
    "sz": "Sálico",
    "ub": "Úrbico",
    "um": "Úmbrico",
    "vr": "Vértico",
    "wc": "Hipocálcico",
}


def catalog_sha256(mapping: dict[str, str]) -> str:
    payload = json.dumps(sorted(mapping.items()), ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def catalog_manifest(mapping: dict[str, str], version: str) -> dict[str, object]:
    return {
        "origin": "versioned_mapping",
        "version": version,
        "record_count": len(mapping),
        "sha256": catalog_sha256(mapping),
    }
