from core.pipelines.censos_economicos.mappings import CLASIFICADOR_CODIGO_MAP

PIPELINE_NAME = "censos_economicos"

RETRYABLE_STATUS_CODES = {429, 500, 502, 503, 504}

NULL_VALUES: list[str] = ["", " ", "NA", "N/A", "NaN", "nan", "*", "X"]

INEGI_STATE_SLUGS: dict[str, str] = {
    "nac": "nac",
    "01": "ags",
    "02": "bc",
    "03": "bcs",
    "04": "camp",
    "05": "coah",
    "06": "col",
    "07": "chis",
    "08": "chih",
    "09": "cdmx",
    "10": "dgo",
    "11": "gto",
    "12": "gro",
    "13": "hgo",
    "14": "jal",
    "15": "mex",
    "16": "mich",
    "17": "mor",
    "18": "nay",
    "19": "nl",
    "20": "oax",
    "21": "pue",
    "22": "qro",
    "23": "qroo",
    "24": "slp",
    "25": "sin",
    "26": "son",
    "27": "tab",
    "28": "tamps",
    "29": "tlax",
    "30": "ver",
    "31": "yuc",
    "32": "zac",
}

CE_YEARS_CONFIG: dict[int, dict] = {
    2018: {
        "url_template": ("https://www.inegi.org.mx/contenidos/programas/ce/2019/Datosabiertos/ce2019_{slug}_csv.zip"),
        "slugs": INEGI_STATE_SLUGS,
        "data_csv_pattern": "conjunto_de_datos/ce2019_{slug}.csv",
        "catalog_actividad": "catalogos/tc_codigo_actividad.csv",
        "catalog_estrato": "catalogos/tc_estrato_ce2019.csv",
        "diccionario": "diccionario_de_datos/",
    },
    2023: {
        "url_template": (
            "https://www.inegi.org.mx/contenidos/programas/ce/2024/"
            "datosabiertos/conjunto_de_datos_ce_{slug}_2024_csv.zip"
        ),
        "slugs": INEGI_STATE_SLUGS,
        "data_csv_pattern": "conjunto_de_datos/tr_ce_{slug}_2024.csv",
        "catalog_actividad": "catalogos/tc_codigo_actividad.csv",
        "catalog_estrato": "catalogos/tc_estrato_ce2024.csv",
        "diccionario": "diccionario_de_datos/diccionario_de_datos_ce2024.csv",
    },
}

RENAME_COLS_2024: dict[str, str] = {
    "ue": "unidades_economicas",
    "h001a": "pers_ocupado_tot",
    "h001b": "pers_ocupado_tot_h",
    "h001c": "pers_ocupado_tot_m",
    "h001d": "horas_pers_ocupado_tot_mh",
    "h000a": "pers_dep_razon_social",
    "h000b": "pers_dep_razon_social_h",
    "h000c": "pers_dep_razon_social_m",
    "h000d": "horas_pers_dep_razon_social_mh",
    "h010a": "pers_remu",
    "h010b": "pers_remu_h",
    "h010c": "pers_remu_m",
    "h010d": "horas_pers_remu_mh",
    "h020a": "pers_no_remu",
    "h020b": "pers_no_remu_h",
    "h020c": "pers_no_remu_m",
    "h020d": "horas_pers_no_remu_mh",
    "h101a": "pers_prod_ventas_servicios",
    "h101b": "pers_prod_ventas_servicios_h",
    "h101c": "pers_prod_ventas_servicios_m",
    "h101d": "horas_pers_prod_ventas_servicios_mh",
    "h203a": "pers_admin_contable_direccion",
    "h203b": "pers_admin_contable_direccion_h",
    "h203c": "pers_admin_contable_direccion_m",
    "h203d": "horas_pers_admin_contable_direccion_mh",
    "i000a": "pers_no_dep_razon_social",
    "i000b": "pers_no_dep_razon_social_h",
    "i000c": "pers_no_dep_razon_social_m",
    "i000d": "horas_pers_no_dep_razon_social_mh",
    "i100a": "pers_contratado_otra_razon_social",
    "i100b": "pers_contratado_otra_razon_social_h",
    "i100c": "pers_contratado_otra_razon_social_m",
    "i100d": "horas_pers_contratado_otra_razon_social_mh",
    "i200a": "pers_honorarios",
    "i200b": "pers_honorarios_h",
    "i200c": "pers_honorarios_m",
    "i200d": "horas_pers_honorarios_mh",
    "j000a": "remuneraciones_tot_mdp",
    "j010a": "salarios_pers_prod_ventas_servicios_mdp",
    "j203a": "sueldos_pers_admin_contable_direccion_mdp",
    "j300a": "contribuciones_seguridad_social_mdp",
    "j400a": "otras_prestaciones_sociales_mdp",
    "j500a": "utilidades_repartidas_mdp",
    "j600a": "indemnizacion_liquidacion_mdp",
    "k000a": "gastos_consu_tot_mdp",
    "k010a": "mercancias_compradas_reventa_mdp",
    "k020a": "materiales_servicios_mdp",
    "k030a": "materias_primas_mdp",
    "k042a": "combustibles_lubricantes_energeticos_mdp",
    "k050a": "renta_alquiler_bienes_mdp",
    "k060a": "servicios_profesionales_mdp",
    "k070a": "maquila_servicios_produccion_mdp",
    "k090a": "otros_bienes_servicios_mdp",
    "k096a": "fletes_productos_vendidos_mdp",
    "k311a": "papeleria_oficina_mdp",
    "k412a": "energia_electrica_mdp",
    "k610a": "pagos_pers_subcontratado_mdp",
    "k620a": "honorarios_comisiones_mdp",
    "k810a": "publicidad_mdp",
    "k820a": "servicios_comunicacion_mdp",
    "k910a": "envases_empaques_mdp",
    "k950a": "reparaciones_refacciones_mdp",
    "k976a": "consu_agua_mdp",
    "m000a": "ingr_tot_mdp",
    "m010a": "ingr_reventa_mercancias_mdp",
    "m020a": "ingr_servicios_profesionales_mdp",
    "m030a": "ingr_venta_productos_mdp",
    "m050a": "ingr_alquiler_bienes_mdp",
    "m090a": "otros_ingr_mdp",
    "m091a": "otros_componentes_prod_bruta_mdp",
    "m700a": "ingr_maquila_terceros_mdp",
    "a111a": "prod_bruta_tot_mdp",
    "a121a": "consu_intermedio_mdp",
    "a131a": "valor_agregado_censal_bruto_mdp",
    "a211a": "inversion_tot_mdp",
    "a221a": "form_brut_cap_mdp",
    "a511a": "mar_por_rev_mdp",
    "a700a": "gastos_tot_mdp",
    "a800a": "ingr_tot_general_mdp",
    "o010a": "valor_productos_elaborados_mdp",
    "o020a": "act_fijos_uso_propio_mdp",
    "p000a": "invent_inic_mdp",
    "p000b": "invent_final_mdp",
    "p000c": "var_exis_mdp",
    "p030a": "invent_inic_proceso_mdp",
    "p030b": "invent_final_proceso_mdp",
    "p030c": "var_invent_proceso_mdp",
    "p100a": "invent_inic_reventa_mdp",
    "p100b": "invent_final_reventa_mdp",
    "q000a": "acervo_act_fijos_mdp",
    "q000b": "depreciacion_act_fijos_mdp",
    "q000c": "compra_act_fijos_mdp",
    "q000d": "ventas_act_fijos_mdp",
    "q010a": "acervo_maquinaria_equipo_mdp",
    "q020a": "acervo_bienes_inmuebles_mdp",
    "q030a": "acervo_unidades_transporte_mdp",
    "q400a": "acervo_equipo_computo_mdp",
    "q900a": "acervo_mobiliario_oficina_mdp",
}

RENAME_COLS_2019: dict[str, str] = {
    "a111a": "prod_bruta_tot_mdp",
    "a112a": "part_bienes_elab_gen_ext_pbt",
    "a113a": "part_imatmpp",
    "a114a": "part_act_fijos_producidos_uso_propio_pb",
    "a115a": "part_var_exist_prod_proceso_pbt",
    "a116a": "part_mar_rev_merc_pbt",
    "a117a": "part_serv_prof_cient_tec_pbt",
    "a118a": "part_ingr_abmi_produccion",
    "a119a": "part_otros_comp_pbt",
    "a121a": "consu_intermedio_mdp",
    "a131a": "valor_agregado_censal_bruto_mdp",
    "a141a": "part_ssen_tr",
    "a143a": "part_salarios_ppvs_tr",
    "a144a": "part_sueldos_pers_acd_tr",
    "a145a": "pers_dependiente_pers_ocup_tot_porcentaje",
    "a146a": "pnr_perasonal_ocupado_tot",
    "a147a": "pnr_po_dependiente",
    "a148a": "prest_soc_util_rep_tot_rem",
    "a149a": "part_urt_tr",
    "a151a": "part_mt_pers_remu",
    "a152a": "part_mt_po_produccion_ventas_servicios",
    "a153a": "part_mt_po_acd",
    "a154a": "prest_soc_tot_rem",
    "a155a": "part_prestaciones_sociales_utilidades_sueldos_salarios",
    "a156a": "part_mt_pfotn",
    "a157a": "tot_prestaciones_ss",
    "a158a": "part_mt_pcpor",
    "a159a": "part_mt_phcs",
    "a171a": "remuneracion_media_per_ocupada_remu",
    "a173a": "salario_pers_operativo_anual",
    "a174a": "sueldo_pers_administrativo_anual",
    "a175a": "pagos_promedio_per_suministrada",
    "a176a": "pagos_promedio_pers_comisiones_u_honorarios",
    "a177a": "part_remuneraciones_gcbs",
    "a179a": "per_no_dep_pers_ocup_tot",
    "a181a": "indem_liqui_remu_tot",
    "a182a": "remuneracion_media_per_remu",
    "a192a": "horas_dia_trab_prom_pers_remu",
    "a193a": "horas_dia_trab_prom_pers_no_remu",
    "a194a": "horas_dia_trab_prom_ppvs",
    "a195a": "horas_dia_trab_prom_empleados_administrativos_control",
    "a197a": "horas_dia_trab_prom_pers_comisiones_honorarios",
    "a201a": "valor_agregado_censal_bruto_pbt",
    "a202a": "part_consu_intermedio_pbt",
    "a204a": "va_promedio_per_ocupada",
    "a206a": "pbt_pers_ocupado_tot",
    "a208a": "part_mpms_gastos_consu_bienes",
    "a209a": "part_mcs_gcbs",
    "a211a": "inversion_tot_mdp",
    "a212a": "part_cae_gcbs",
    "a213a": "inversion_ti_tot",
    "a214a": "part_gastos_consu_otros_bienes_servicios_gastos_consu",
    "a215a": "inversion_tot_act_fijos",
    "a216a": "part_ivm_ti_suministro_bienes",
    "a217a": "inversion_tot_valor_agregado_censal_bruto",
    "a218a": "part_servi_prof_cient",
    "a219a": "part_otros_isbs_ti",
    "a221a": "form_brut_cap_mdp",
    "a222a": "inversion_tot_pbt",
    "a223a": "part_venta_productos_elaborados_generados_o_extraidos_tot",
    "a224a": "part_ingr_abmi_tot",
    "a225a": "part_imatmpp_2",
    "a226a": "part_mep_tot_act_fijos",
    "a227a": "part_cif_tot_act_fijos",
    "a228a": "part_et_tot_act_fijos",
    "a229a": "part_ecp_tot_act_fijos",
    "a231a": "margen_bruto_operacion",
    "a235a": "ing_princ_por_sum_bienes",
    "a236a": "gp_gcbs",
    "a237a": "gp_ip",
    "a238a": "part_meo_otros_act_fijos_tot",
    "a242a": "valor_act_fijos_per_ocupada",
    "a243a": "maqui_equip_prod_a_prod_tot",
    "a244a": "acti_fijo_brut_tot",
    "a245a": "forma_brut_cap_fijo_acervo_tot",
    "a247a": "produccion_act_fijos_uso_propio_compras_act_fijos",
    "a248a": "otros_isbs_ti_suministro",
    "a252a": "gastos_no_derivados_actividad_gcbs",
    "a253a": "ingr_no_derivados_actividad_isbs",
    "a256a": "valor_promedio_maquinaria_equipo_per_ocupada_anuales",
    "a433a": "ip_respecto_gp",
    "a434a": "porcentaje_ip_ti_actividad_financieros",
    "a436a": "isbs_per_ocupada",
    "a511a": "mar_por_rev_mdp",
    "a529a": "part_depreciacion_valor_act_fijos",
    "a534a": "tasa_rentabilidad_promedio",
    "a700a": "gastos_tot_mdp",
    "a747a": "salario_promedio_diarios_per_operativa",
    "a748a": "sueldo_promedio_diario_per_administrativa",
    "a752a": "va_tot_act_fijos",
    "a764a": "part_muje_pers_ocupado_tot",
    "a800a": "ingr_tot_general_mdp",
    "h000a": "pers_dep_razon_social",
    "h000b": "pers_dep_razon_social_h",
    "h000c": "pers_dep_razon_social_m",
    "h000d": "horas_pers_dep_razon_social_mh",
    "h001a": "pers_ocupado_tot",
    "h001b": "pers_ocupado_tot_h",
    "h001c": "pers_ocupado_tot_m",
    "h001d": "horas_pers_ocupado_tot_mh",
    "h010a": "pers_remu",
    "h010b": "pers_remu_h",
    "h010c": "pers_remu_m",
    "h010d": "horas_pers_remu_mh",
    "h020a": "pers_no_remu",
    "h020b": "pers_no_remu_h",
    "h020c": "pers_no_remu_m",
    "h020d": "horas_pers_no_remu_mh",
    "h101a": "pers_prod_ventas_servicios",
    "h101b": "pers_prod_ventas_servicios_h",
    "h101c": "pers_prod_ventas_servicios_m",
    "h101d": "horas_pers_prod_ventas_servicios_mh",
    "h203a": "pers_admin_contable_direccion",
    "h203b": "pers_admin_contable_direccion_h",
    "h203c": "pers_admin_contable_direccion_m",
    "h203d": "horas_pers_admin_contable_direccion_mh",
    "i000a": "pers_no_dep_razon_social",
    "i000b": "pers_no_dep_razon_social_h",
    "i000c": "pers_no_dep_razon_social_m",
    "i000d": "horas_pers_no_dep_razon_social_mh",
    "i100a": "pers_contratado_otra_razon_social",
    "i100b": "pers_contratado_otra_razon_social_h",
    "i100c": "pers_contratado_otra_razon_social_m",
    "i100d": "horas_pers_contratado_otra_razon_social_mh",
    "i200a": "pers_honorarios",
    "i200b": "pers_honorarios_h",
    "i200c": "pers_honorarios_m",
    "i200d": "horas_pers_honorarios_mh",
    "j000a": "remuneraciones_tot_mdp",
    "j010a": "salarios_pers_prod_ventas_servicios_mdp",
    "j203a": "sueldos_pers_admin_contable_direccion_mdp",
    "j300a": "contribuciones_seguridad_social_mdp",
    "j400a": "otras_prestaciones_sociales_mdp",
    "j500a": "utilidades_repartidas_mdp",
    "j600a": "indemnizacion_liquidacion_mdp",
    "k000a": "gastos_consu_tot_mdp",
    "k010a": "mercancias_compradas_reventa_mdp",
    "k020a": "materiales_servicios_mdp",
    "k030a": "materias_primas_mdp",
    "k042a": "combustibles_lubricantes_energeticos_mdp",
    "k050a": "renta_alquiler_bienes_mdp",
    "k060a": "servicios_profesionales_mdp",
    "k070a": "maquila_servicios_produccion_mdp",
    "k090a": "otros_bienes_servicios_mdp",
    "k096a": "fletes_productos_vendidos_mdp",
    "k311a": "papeleria_oficina_mdp",
    "k412a": "energia_electrica_mdp",
    "k610a": "pagos_pers_subcontratado_mdp",
    "k620a": "honorarios_comisiones_mdp",
    "k810a": "publicidad_mdp",
    "k820a": "servicios_comunicacion_mdp",
    "k910a": "envases_empaques_mdp",
    "k950a": "reparaciones_refacciones_mdp",
    "k976a": "consu_agua_mdp",
    "m000a": "ingr_tot_mdp",
    "m010a": "ingr_reventa_mercancias_mdp",
    "m020a": "ingr_servicios_profesionales_mdp",
    "m030a": "ingr_venta_productos_mdp",
    "m050a": "ingr_alquiler_bienes_mdp",
    "m090a": "otros_ingr_mdp",
    "m091a": "otros_componentes_prod_bruta_mdp",
    "m700a": "ingr_maquila_terceros_mdp",
    "o010a": "valor_productos_elaborados_mdp",
    "o020a": "act_fijos_uso_propio_mdp",
    "p000a": "invent_inic_mdp",
    "p000b": "invent_final_mdp",
    "p000c": "var_exis_mdp",
    "p030a": "invent_inic_proceso_mdp",
    "p030b": "invent_final_proceso_mdp",
    "p030c": "var_invent_proceso_mdp",
    "p100a": "invent_inic_reventa_mdp",
    "p100b": "invent_final_reventa_mdp",
    "q000a": "acervo_act_fijos_mdp",
    "q000b": "depreciacion_act_fijos_mdp",
    "q000c": "compra_act_fijos_mdp",
    "q000d": "ventas_act_fijos_mdp",
    "q010a": "acervo_maquinaria_equipo_mdp",
    "q020a": "acervo_bienes_inmuebles_mdp",
    "q030a": "acervo_unidades_transporte_mdp",
    "q400a": "acervo_equipo_computo_mdp",
    "q900a": "acervo_mobiliario_oficina_mdp",
    "ue": "unidades_economicas",
}

RENAME_COLS_BY_YEAR: dict[int, dict[str, str]] = {
    2018: RENAME_COLS_2019,
    2023: RENAME_COLS_2024,
}

COLUMN_DESCRIPTIONS_2024: dict[str, str] = {
    "ue": "Unidades economicas",
    "h001a": "Personal ocupado total",
    "h001b": "Personal ocupado total, hombres",
    "h001c": "Personal ocupado total, mujeres",
    "h001d": "Horas trabajadas por personal ocupado total (miles de horas)",
    "h000a": "Personal dependiente de la razon social total",
    "h000b": "Personal dependiente de la razon social, hombres",
    "h000c": "Personal dependiente de la razon social, mujeres",
    "h000d": "Horas trabajadas por personal dependiente de la razon social (miles de horas)",
    "h010a": "Personal remunerado total",
    "h010b": "Personal remunerado, hombres",
    "h010c": "Personal remunerado, mujeres",
    "h010d": "Horas trabajadas por personal remunerado (miles de horas)",
    "h020a": "Personas propietarias, familiares y otro personal no remunerado total",
    "h020b": "Personas propietarias, familiares y otro personal no remunerado, hombres",
    "h020c": "Personas propietarias, familiares y otro personal no remunerado, mujeres",
    "h020d": "Horas trabajadas por personal no remunerado (miles de horas)",
    "h101a": "Personal de produccion, ventas y servicios total",
    "h101b": "Personal de produccion, ventas y servicios, hombres",
    "h101c": "Personal de produccion, ventas y servicios, mujeres",
    "h101d": "Horas trabajadas por personal de produccion, ventas y servicios (miles de horas)",
    "h203a": "Personal administrativo, contable y de direccion total",
    "h203b": "Personal administrativo, contable y de direccion, hombres",
    "h203c": "Personal administrativo, contable y de direccion, mujeres",
    "h203d": "Horas trabajadas por personal administrativo, contable y de direccion (miles de horas)",
    "i000a": "Personal no dependiente de la razon social total",
    "i000b": "Personal no dependiente de la razon social, hombres",
    "i000c": "Personal no dependiente de la razon social, mujeres",
    "i000d": "Horas trabajadas por personal no dependiente de la razon social (miles de horas)",
    "i100a": "Personal contratado y proporcionado por otra razon social total",
    "i100b": "Personal contratado y proporcionado por otra razon social, hombres",
    "i100c": "Personal contratado y proporcionado por otra razon social, mujeres",
    "i100d": "Horas trabajadas por personal contratado por otra razon social (miles de horas)",
    "i200a": "Personal por honorarios o comisiones sin sueldo o salario fijo total",
    "i200b": "Personal por honorarios o comisiones sin sueldo o salario fijo, hombres",
    "i200c": "Personal por honorarios o comisiones sin sueldo o salario fijo, mujeres",
    "i200d": "Horas trabajadas por personal por honorarios (miles de horas)",
    "j000a": "Total de remuneraciones (millones de pesos)",
    "j010a": "Total de salarios al personal de produccion, ventas y servicios (millones de pesos)",
    "j203a": "Total de sueldos al personal administrativo, contable y de direccion (millones de pesos)",
    "j300a": "Contribuciones patronales a regimenes de seguridad social (millones de pesos)",
    "j400a": "Otras prestaciones sociales (millones de pesos)",
    "j500a": "Utilidades repartidas al personal (millones de pesos)",
    "j600a": "Gastos por indemnizacion o liquidacion del personal (millones de pesos)",
    "k000a": "Total de gastos por consumo de bienes y servicios (millones de pesos)",
    "k010a": "Mercancias y bienes comprados para la reventa (millones de pesos)",
    "k020a": "Materiales e insumos consumidos para la prestacion de servicios (millones de pesos)",
    "k030a": "Materias primas y materiales que se integran a la produccion (millones de pesos)",
    "k042a": "Consumo de combustibles, lubricantes y energeticos (millones de pesos)",
    "k050a": "Renta y alquiler de bienes muebles e inmuebles (millones de pesos)",
    "k060a": "Contratacion de servicios profesionales, cientificos y tecnicos (millones de pesos)",
    "k070a": "Maquila y servicios de produccion de bienes por contrato (millones de pesos)",
    "k090a": "Consumo de otros bienes y servicios (millones de pesos)",
    "k096a": "Fletes de productos vendidos (millones de pesos)",
    "k311a": "Gastos por consumo de papeleria y articulos de oficina (millones de pesos)",
    "k412a": "Gasto por consumo de energia electrica (millones de pesos)",
    "k610a": "Pagos a otra razon social que contrato y proporciono personal (millones de pesos)",
    "k620a": "Gastos por honorarios o comisiones sin sueldo o salario fijo (millones de pesos)",
    "k810a": "Gastos por publicidad (millones de pesos)",
    "k820a": "Gastos por servicios de comunicacion (millones de pesos)",
    "k910a": "Gastos por consumo de envases y empaques (millones de pesos)",
    "k950a": "Reparaciones y refacciones para mantenimiento corriente (millones de pesos)",
    "k976a": "Consumo de agua (millones de pesos)",
    "m000a": "Total de ingresos por suministro de bienes y servicios (millones de pesos)",
    "m010a": "Ingresos por la reventa de mercancias y bienes (millones de pesos)",
    "m020a": "Ingresos por prestacion de servicios profesionales, cientificos y tecnicos (millones de pesos)",
    "m030a": "Venta de productos elaborados, generados o extraidos (millones de pesos)",
    "m050a": "Ingresos por alquiler de bienes muebles e inmuebles (millones de pesos)",
    "m090a": "Otros ingresos por suministro de bienes y servicios (millones de pesos)",
    "m091a": "Otros componentes de la produccion bruta total (millones de pesos)",
    "m700a": "Ingresos por maquilar o transformar materias primas propiedad de terceros (millones de pesos)",
    "a111a": "Produccion bruta total (millones de pesos)",
    "a121a": "Consumo intermedio (millones de pesos)",
    "a131a": "Valor agregado censal bruto (millones de pesos)",
    "a211a": "Inversion total (millones de pesos)",
    "a221a": "Formacion bruta de capital fijo (millones de pesos)",
    "a511a": "Margen por reventa de mercancias (millones de pesos)",
    "a700a": "Total de gastos (millones de pesos)",
    "a800a": "Total de ingresos (millones de pesos)",
    "o010a": "Valor de productos elaborados, bienes generados y extraidos (millones de pesos)",
    "o020a": "Activos fijos producidos para uso propio (millones de pesos)",
    "p000a": "Total de inventario inicial (millones de pesos)",
    "p000b": "Total de inventario final (millones de pesos)",
    "p000c": "Variacion total de existencias (millones de pesos)",
    "p030a": "Total de inventario inicial de productos en proceso (millones de pesos)",
    "p030b": "Total de inventario final de productos en proceso (millones de pesos)",
    "p030c": "Variacion de inventarios de productos en proceso (millones de pesos)",
    "p100a": "Total de inventario inicial de mercancias compradas para reventa (millones de pesos)",
    "p100b": "Total de inventario final de mercancias compradas para reventa (millones de pesos)",
    "q000a": "Acervo total de activos fijos (millones de pesos)",
    "q000b": "Depreciacion total de activos fijos (millones de pesos)",
    "q000c": "Compra y adquisicion total de activos fijos y reformas mayores (millones de pesos)",
    "q000d": "Ventas totales de activos fijos (millones de pesos)",
    "q010a": "Acervo total de maquinaria y equipo de produccion (millones de pesos)",
    "q020a": "Acervo total de bienes inmuebles (millones de pesos)",
    "q030a": "Acervo total de unidades y equipo de transporte (millones de pesos)",
    "q400a": "Acervo total de equipo de computo y perifericos (millones de pesos)",
    "q900a": "Acervo total de mobiliario, equipo de oficina y otros activos fijos (millones de pesos)",
}

COLUMN_DESCRIPTIONS_2019: dict[str, str] = {
    **COLUMN_DESCRIPTIONS_2024,
    "a112a": "Participacion del valor de bienes elaborados, generados o extraidos en la produccion bruta total",
    "a113a": "Participacion de ingresos por maquilar o transformar materias primas propiedad de terceros",
    "a114a": "Participacion de activos fijos producidos para uso propio en la produccion bruta",
    "a115a": "Participacion de la variacion de existencias de productos en proceso en la produccion bruta total",
    "a116a": "Participacion del margen por reventa de mercancias en la produccion bruta total",
    "a117a": "Participacion de servicios profesionales, cientificos y tecnicos en la produccion bruta",
    "a118a": "Participacion de ingresos por alquiler de bienes muebles e inmuebles en la produccion",
    "a119a": "Participacion de otros componentes de la produccion bruta total",
    "a141a": "Participacion de salarios y sueldos en el total de remuneraciones",
    "a143a": "Participacion de salarios al personal de produccion, ventas y servicios en el total de remuneraciones",
    "a144a": "Participacion de sueldos al personal administrativo, contable y de direccion en el total de remuneraciones",
    "a145a": "Personal dependiente sobre personal ocupado total (porcentaje)",
    "a146a": "Personal no remunerado sobre personal ocupado total",
    "a147a": "Personal no remunerado sobre personal ocupado dependiente",
    "a148a": "Prestaciones sociales y utilidades repartidas sobre el total de remuneraciones",
    "a149a": "Participacion de utilidades repartidas a trabajadores en el total de remuneraciones",
    "a151a": "Participacion de mujeres en el total de personal remunerado",
    "a152a": "Participacion de mujeres en el total de personal de produccion, ventas y servicios",
    "a153a": "Participacion de mujeres en el total de personal administrativo, contable y de direccion",
    "a154a": "Prestaciones sociales sobre el total de remuneraciones",
    "a155a": "Participacion de prestaciones sociales y utilidades sobre sueldos y salarios",
    "a156a": "Participacion de mujeres en el total de propietarios, familiares y otros trabajadores no remunerados",
    "a157a": "Total de prestaciones sobre salarios y sueldos",
    "a158a": "Participacion de mujeres en el total de personal contratado y proporcionado por otra razon social",
    "a159a": "Participacion de mujeres en el total de personal por honorarios o comisiones sin sueldo fijo",
    "a171a": "Remuneracion media por persona ocupada remunerada",
    "a173a": "Salario al personal operativo (anual)",
    "a174a": "Sueldo al personal administrativo (anual)",
    "a175a": "Pagos promedio por persona suministrada",
    "a176a": "Pagos promedio al personal por comisiones u honorarios",
    "a177a": "Participacion de remuneraciones en gastos por consumo de bienes y servicios",
    "a179a": "Personal no dependiente sobre personal ocupado total",
    "a181a": "Indemnizaciones y liquidaciones sobre remuneraciones totales",
    "a182a": "Remuneracion media por persona remunerada",
    "a192a": "Horas diarias trabajadas promedio por personal remunerado",
    "a193a": "Horas diarias trabajadas promedio por personal no remunerado",
    "a194a": "Horas diarias trabajadas promedio por personal de produccion, ventas y servicios",
    "a195a": "Horas diarias trabajadas promedio por empleados administrativos y de control",
    "a197a": "Horas diarias trabajadas promedio por personal por comisiones u honorarios",
    "a201a": "Valor agregado censal bruto sobre la produccion bruta total",
    "a202a": "Participacion del consumo intermedio en la produccion bruta total",
    "a204a": "Valor agregado promedio por persona ocupada",
    "a206a": "Produccion bruta total sobre personal ocupado total",
    "a208a": "Participacion de materias primas, materiales y suministros en gastos por consumo de bienes",
    "a209a": "Participacion de maquila y contratacion de servicios en gastos por consumo de bienes y servicios",
    "a212a": "Participacion del consumo de agua y energeticos en gastos por consumo de bienes y servicios",
    "a213a": "Inversion total sobre ingresos totales",
    "a214a": "Participacion de gastos por consumo de otros bienes y servicios en gastos por consumo",
    "a215a": "Inversion total sobre activos fijos",
    "a216a": "Participacion de ingresos por venta de mercancias en el total de ingresos por suministro de bienes",
    "a217a": "Inversion total sobre valor agregado censal bruto",
    "a218a": "Participacion de servicios profesionales, cientificos y tecnicos en el total de ingresos",
    "a219a": "Participacion de otros ingresos por suministro de bienes y servicios en el total de ingresos",
    "a222a": "Inversion total sobre la produccion bruta total",
    "a223a": "Participacion de la venta de productos elaborados, generados o extraidos en el total",
    "a224a": "Participacion de ingresos por alquiler de bienes muebles e inmuebles en el total",
    "a225a": "Participacion de ingresos por maquilar o transformar materias primas propiedad de terceros (2)",
    "a226a": "Participacion de maquinaria y equipo de produccion en el total de activos fijos",
    "a227a": "Participacion de construcciones e instalaciones fijas en el total de activos fijos",
    "a228a": "Participacion del equipo de transporte en el total de activos fijos",
    "a229a": "Participacion del equipo de computo y perifericos en el total de activos fijos",
    "a231a": "Margen bruto de operacion",
    "a235a": "Ingreso principal sobre ingresos por suministro de bienes y servicios",
    "a236a": "Gasto principal sobre gastos por consumo de bienes y servicios",
    "a237a": "Gasto principal sobre ingreso principal",
    "a238a": "Participacion de mobiliario y equipo de oficina y otros activos fijos en el total",
    "a242a": "Valor de activos fijos por persona ocupada",
    "a243a": "Maquinaria y equipo de produccion sobre la produccion bruta total",
    "a244a": "Activos fijos sobre la produccion bruta total",
    "a245a": "Formacion bruta de capital fijo sobre acervo de capital",
    "a247a": "Produccion de activos fijos para uso propio sobre compras de activos fijos",
    "a248a": "Otros ingresos por suministro de bienes y servicios sobre el total de ingresos por suministro",
    "a252a": "Gastos no derivados de la actividad sobre gastos por consumo de bienes y servicios",
    "a253a": "Ingresos no derivados de la actividad sobre ingresos por suministro de bienes y servicios",
    "a256a": "Valor promedio de maquinaria y equipo por persona ocupada (anuales)",
    "a433a": "Ingreso principal respecto al gasto principal",
    "a434a": "Porcentaje del ingreso principal en el total de ingresos por actividades financieras",
    "a436a": "Ingresos por suministro de bienes y servicios por persona ocupada",
    "a529a": "Participacion de la depreciacion en el valor de activos fijos",
    "a534a": "Tasa de rentabilidad promedio",
    "a747a": "Salario promedio diario por persona operativa",
    "a748a": "Sueldo promedio diario por persona administrativa",
    "a752a": "Valor agregado total sobre activos fijos",
    "a764a": "Participacion de mujeres en el personal ocupado total",
}

COLUMN_DESCRIPTIONS_BY_YEAR: dict[int, dict[str, str]] = {
    2018: COLUMN_DESCRIPTIONS_2019,
    2023: COLUMN_DESCRIPTIONS_2024,
}

GEO_LEVEL_NACIONAL = "nacional"
GEO_LEVEL_ESTATAL = "estatal"
GEO_LEVEL_MUNICIPAL = "municipal"

GEO_RENAME_2019: dict[str, str] = {}
GEO_RENAME_2024: dict[str, str] = {"e03": "entidad", "e04": "municipio"}

EXTRA_COLS_2024: list[str] = ["sector", "subsector", "rama", "subrama", "clase"]

TOTAL_ROW_CODIGO: str = "TOTAL DE SECTOR"

CLASIFICADOR_TEXT_TO_ID: dict[str, int] = {v.lower(): k for k, v in CLASIFICADOR_CODIGO_MAP.items()}

ENTITY_CHUNK_SIZE: int = 4
