CREATE TABLE IF NOT EXISTS establecimientos (
    clues VARCHAR(11) NOT NULL,
    fecha_actualizacion DATE NOT NULL,
    institucion_id INTEGER REFERENCES instituciones(id),
    entidad_id  INTEGER,
    municipio_id INTEGER,
    localidad_id INTEGER REFERENCES localidades(id),
    jurisdiccion_id INTEGER REFERENCES jurisdicciones(id),
    tipo_establecimiento_id INTEGER REFERENCES tipos_establecimiento(id),
    tipologia_id INTEGER REFERENCES tipologias(id),
    subtipologia_id INTEGER REFERENCES subtipologias(id),
    unidad_movil_id INTEGER REFERENCES unidades_moviles(id),
    vialidad_id INTEGER REFERENCES vialidades(id),
    numero_exterior TEXT,
    numero_interior TEXT,
    tipo_asentamiento_id INTEGER REFERENCES tipos_asentamiento(id),
    estatus_id INTEGER REFERENCES estatus_establecimiento(id),
    nivel_atencion_id INTEGER REFERENCES nivel_atencion(id),
    estrato_unidad_id INTEGER REFERENCES estrato_unidad(id),
    tipo_obra_id INTEGER REFERENCES tipos_obra(id),
    instituto_adm_id INTEGER REFERENCES institutos_administracion(id),
    rfc_id INTEGER REFERENCES rfc_establecimientos(id),
    marca_movil_id INTEGER REFERENCES marcas_moviles(id),
    programa_movil_id  INTEGER REFERENCES programas_moviles(id),
    tipo_unidad_movil_id  INTEGER REFERENCES tipos_unidad_movil(id),
    tipologia_movil_id  INTEGER REFERENCES tipologias_moviles(id),
    movimiento_id INTEGER REFERENCES movimientos(id),
    fecha_ultimo_movimiento DATE,
    motivo_baja_id INTEGER REFERENCES motivos_baja(id),
    fecha_efectiva_baja DATE,
    telefono_1 TEXT,
    extension_1 TEXT,
    telefono_2 TEXT,
    extension_2 TEXT,
    fecha_construccion DATE,
    fecha_inicio_operacion  DATE,
    latitud FLOAT,
    longitud FLOAT,

    CONSTRAINT pk_establecimientos PRIMARY KEY (clues, fecha_actualizacion)
);
