CREATE TABLE IF NOT EXISTS establecimientos (
    clues VARCHAR(11) NOT NULL,
    fecha_actualizacion DATE NOT NULL,
    institucion_id INTEGER NOT NULL REFERENCES instituciones(id),
    entidad_id  INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    localidad_id INTEGER NOT NULL REFERENCES localidades(id),
    jurisdiccion_id INTEGER REFERENCES jurisdicciones(id),
    tipo_establecimiento_id VARCHAR(20) REFERENCES tipos_establecimiento(id),
    tipologia_id INTEGER REFERENCES tipologias(id),
    subtipologia_id INTEGER REFERENCES subtipologias(id),
    unidad_movil_id INTEGER REFERENCES unidades_moviles(id),
    vialidad_id INTEGER REFERENCES vialidades(id),
    numero_exterior VARCHAR(30),
    numero_interior VARCHAR(30),
    tipo_asentamiento_id VARCHAR(20) REFERENCES tipos_asentamiento(id),
    estatus_id VARCHAR(20) REFERENCES estatus_establecimiento(id),
    nivel_atencion_id VARCHAR(20) REFERENCES nivel_atencion(id),
    estrato_unidad_id VARCHAR(20) REFERENCES estrato_unidad(id),
    tipo_obra_id VARCHAR(20) REFERENCES tipos_obra(id),
    instituto_adm_id INTEGER REFERENCES institutos_administracion(id),
    rfc_id INTEGER REFERENCES rfc_establecimientos(id),
    marca_movil_id INTEGER REFERENCES marcas_moviles(id),
    programa_movil_id  INTEGER REFERENCES programas_moviles(id),
    tipo_unidad_movil_id  INTEGER REFERENCES tipos_unidad_movil(id),
    tipologia_movil_id  INTEGER REFERENCES tipologias_moviles(id),
    movimiento_id INTEGER REFERENCES movimientos(id),
    fecha_ultimo_movimiento DATE,
    motivo_baja_id INTEGER REFERENCES motivos_baja(id),
    fecha_efectiva_baja DATE,
    telefono_1  VARCHAR(20),
    extension_1  VARCHAR(10),
    telefono_2  VARCHAR(20),
    extension_2  VARCHAR(10),
    fecha_construccion DATE,
    fecha_inicio_operacion  DATE,
    latitud FLOAT,
    longitud FLOAT,

    CONSTRAINT pk_establecimientos PRIMARY KEY (clues, fecha_actualizacion)
);
