DATA_FIELD = "carga_de_datos"
DATASETS_FIELD = "conunto_datos"
DEPENDENCIA_PATH = ("datos", "general", "nombre_de_la_dependencia")
CONJUNTO_PATH = ("datos", "general", "nombre_del_conjunto_de_datos")
FECHA_CORTE_FIELD = "fecha_de_corte_del_archivo"
FECHA_ACTUALIZACION_FIELD = "fecha_de_actualizacion"
ESTADO_ENVIADO = "enviado"
ACERVO_CONNECT_TIMEOUT = 5
ACERVO_READ_TIMEOUT = 30
ACERVO_MAX_ATTEMPTS = 3
