from typing import Final

DEFUNCIONES_ACCENT_MAP: Final[dict[str, str]] = {
    r"\bACIDO\b": "ÁCIDO",
    r"\bAMNESICO\b": "AMNÉSICO",
    r"\bATROFICA\b": "ATRÓFICA",
    r"\bATROFICAS\b": "ATRÓFICAS",
    r"\bATROFICO\b": "ATRÓFICO",
    r"\bBASICO\b": "BÁSICO",
    r"\bCARDIACA\b": "CARDÍACA",
    r"\bCARDIACAS\b": "CARDÍACAS",
    r"\bCARDIACO\b": "CARDÍACO",
    r"\bCLINICA\b": "CLÍNICA",
    r"\bCLINICO\b": "CLÍNICO",
    r"\bCODIGO\b": "CÓDIGO",
    r"\bCONGENITA\b": "CONGÉNITA",
    r"\bCONGENITAS\b": "CONGÉNITAS",
    r"\bCONGENITO\b": "CONGÉNITO",
    r"\bCONGENITOS\b": "CONGÉNITOS",
    r"\bCONSTIPACION\b": "CONSTIPACIÓN",
    r"\bCORAZON\b": "CORAZÓN",
    r"\bCRANEO\b": "CRÁNEO",
    r"\bCRONICA\b": "CRÓNICA",
    r"\bCRONICAS\b": "CRÓNICAS",
    r"\bCRONICO\b": "CRÓNICO",
    r"\bCRONICOS\b": "CRÓNICOS",
    r"\bCRONOLOGICA\b": "CRONOLÓGICA",
    r"\bDIAGNOSTICO\b": "DIAGNÓSTICO",
    r"\bEMBRION\b": "EMBRIÓN",
    r"\bESOFAGO\b": "ESÓFAGO",
    r"\bESPECIFICA\b": "ESPECÍFICA",
    r"\bESPECIFICACION\b": "ESPECIFICACIÓN",
    r"\bESPECIFICO\b": "ESPECÍFICO",
    r"\bESTOMAGO\b": "ESTÓMAGO",
    r"\bHEMATOLOGICO\b": "HEMATOLÓGICO",
    r"\bHEMATOLOGICOS\b": "HEMATOLÓGICOS",
    r"\bHEMATOPOYETICOS\b": "HEMATOPOYÉTICOS",
    r"\bHIGADO\b": "HÍGADO",
    r"\bINFECCION\b": "INFECCIÓN",
    r"\bISQUEMICA\b": "ISQUÉMICA",
    r"\bISQUEMICAS\b": "ISQUÉMICAS",
    r"\bISQUEMICO\b": "ISQUÉMICO",
    r"\bLINFATICO\b": "LINFÁTICO",
    r"\bLINFATICOS\b": "LINFÁTICOS",
    r"\bMEDICA\b": "MÉDICA",
    r"\bMEDICO\b": "MÉDICO",
    r"\bMUSCULO\b": "MÚSCULO",
    r"\bMUSCULOS\b": "MÚSCULOS",
    r"\bNEUMONIA\b": "NEUMONÍA",
    r"\bORGANICA\b": "ORGÁNICA",
    r"\bORGANICAS\b": "ORGÁNICAS",
    r"\bORGANICO\b": "ORGÁNICO",
    r"\bORGANICOS\b": "ORGÁNICOS",
    r"\bORGANO\b": "ÓRGANO",
    r"\bORGANOS\b": "ÓRGANOS",
    r"\bPANCREAS\b": "PÁNCREAS",
    r"\bPARALISIS\b": "PARÁLISIS",
    r"\bPATOLOGICA\b": "PATOLÓGICA",
    r"\bPATOLOGICO\b": "PATOLÓGICO",
    r"\bPROSTATA\b": "PRÓSTATA",
    r"\bREGION\b": "REGIÓN",
    r"\bRIÑON\b": "RIÑÓN",
    r"\bSINDROME\b": "SÍNDROME",
    r"\bTORAX\b": "TÓRAX",
    r"\bTOXICA\b": "TÓXICA",
    r"\bTOXICO\b": "TÓXICO",
    r"\bTRAQUEA\b": "TRÁQUEA",
    r"\bULCERA\b": "ÚLCERA",
    r"\bULCERAS\b": "ÚLCERAS",
    r"\bUTERO\b": "ÚTERO",
    r"\bVESICULA\b": "VESÍCULA",
}

DEFUNCIONES_ACRONYMS: Final[tuple[str, ...]] = (
    "IMSS",
    "ISSSTE",
    "PEMEX",
    "SEDENA",
    "SEMAR",
    "ISSFAM",
    "OPD",
    "PROSPERA",
    "CIE",
)

DEFUNCIONES_PROPER_NAMES: Final[tuple[str, ...]] = (
    "Alzheimer",
    "Parkinson",
    "Marfan",
    "Crohn",
    "Down",
)

DEFUNCIONES_CANONICAL_TOKENS: Final[tuple[str, ...]] = (
    *DEFUNCIONES_ACRONYMS,
    *DEFUNCIONES_PROPER_NAMES,
)
