-- =======================================================================
-- V13: microdato del certificado de nacimiento
-- =======================================================================

CREATE UNLOGGED TABLE IF NOT EXISTS stg_nacimientos_certificados (
	id SERIAL NOT NULL,
	anio SMALLINT NOT NULL,
	fecha_nacimiento DATE,
	hora_nacimiento TIME WITHOUT TIME ZONE,
	cve_geo INTEGER NOT NULL,
	localidad_residencia_id INTEGER,
	edad_madre SMALLINT,
	edad_padre SMALLINT,
	se_considera_indigena_id INTEGER,
	habla_lengua_indigena_id INTEGER,
	estado_conyugal_id INTEGER,
	escolaridad_id INTEGER,
	interrumpio_estudios_id INTEGER,
	ocupacion_habitual_id INTEGER,
	trabaja_actualmente_id INTEGER,
	afiliacion_id INTEGER,
	numero_embarazos SMALLINT,
	atencion_prenatal_id INTEGER,
	total_consultas SMALLINT,
	sobrevivio_parto_id INTEGER,
	sexo_id INTEGER,
	edad_gestacional SMALLINT,
	talla SMALLINT,
	peso SMALLINT,
	producto_embarazo_id INTEGER,
	orden_producto SMALLINT,
	total_productos SMALLINT,
	diagnostico_1_id INTEGER,
	diagnostico_2_id INTEGER,
	lugar_nacimiento_id INTEGER,
	establecimiento_salud_id INTEGER,
	tiempo_traslado_minutos SMALLINT,
	resolucion_embarazo_id INTEGER,
	entidad_parto_id INTEGER,
	municipio_parto_id INTEGER,
	localidad_parto_id INTEGER,
	fecha_actualizacion DATE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(localidad_residencia_id) REFERENCES cat_localidad (id),
	FOREIGN KEY(se_considera_indigena_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(habla_lengua_indigena_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(estado_conyugal_id) REFERENCES cat_estado_conyugal (id),
	FOREIGN KEY(escolaridad_id) REFERENCES cat_escolaridad (id),
	FOREIGN KEY(interrumpio_estudios_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(ocupacion_habitual_id) REFERENCES cat_ocupacion_habitual (id),
	FOREIGN KEY(trabaja_actualmente_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(afiliacion_id) REFERENCES cat_afiliacion (id),
	FOREIGN KEY(atencion_prenatal_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(sobrevivio_parto_id) REFERENCES cat_si_no (id),
	FOREIGN KEY(sexo_id) REFERENCES cat_sexo (id),
	FOREIGN KEY(producto_embarazo_id) REFERENCES cat_producto_embarazo (id),
	FOREIGN KEY(diagnostico_1_id) REFERENCES cat_diagnostico (id),
	FOREIGN KEY(diagnostico_2_id) REFERENCES cat_diagnostico (id),
	FOREIGN KEY(lugar_nacimiento_id) REFERENCES cat_lugar_nacimiento (id),
	FOREIGN KEY(establecimiento_salud_id) REFERENCES cat_establecimiento_salud (id),
	FOREIGN KEY(resolucion_embarazo_id) REFERENCES cat_resolucion_embarazo (id),
	FOREIGN KEY(entidad_parto_id) REFERENCES cat_entidad (id),
	FOREIGN KEY(municipio_parto_id) REFERENCES cat_municipio (id),
	FOREIGN KEY(localidad_parto_id) REFERENCES cat_localidad (id)
);

CREATE INDEX IF NOT EXISTS ix_stg_nacimientos_certificados_cve_geo ON stg_nacimientos_certificados (cve_geo);
CREATE INDEX IF NOT EXISTS ix_stg_nacimientos_certificados_anio ON stg_nacimientos_certificados (anio);
