-- Generado desde core/pipelines/defunciones_inegi/schemas.py
CREATE TABLE stg_defunciones (
	id SERIAL NOT NULL,
	edicion_id INTEGER NOT NULL,
	entidad_registro_id SMALLINT,
	municipio_registro_id SMALLINT,
	entidad_residencia_id SMALLINT,
	municipio_residencia_id SMALLINT,
	entidad_ocurrencia_id SMALLINT,
	municipio_ocurrencia_id SMALLINT,
	entidad_lesion_id SMALLINT,
	municipio_lesion_id SMALLINT,
	localidad_residencia_id INTEGER,
	localidad_ocurrencia_id INTEGER,
	localidad_lesion_id INTEGER,
	tamanio_localidad_residencia_id INTEGER,
	tamanio_localidad_ocurrencia_id INTEGER,
	fecha_ocurrencia DATE,
	fecha_registro DATE,
	fecha_nacimiento DATE,
	fecha_certificacion DATE,
	hora_defuncion TIME WITHOUT TIME ZONE,
	edad_cantidad SMALLINT,
	edad_unidad SMALLINT,
	causa_defuncion_id INTEGER,
	causa_materna_id INTEGER,
	capitulo_grupo_id INTEGER,
	lista_cie_id INTEGER,
	lista_mexicana_id INTEGER,
	grupo_lista_mexicana_id INTEGER,
	sexo_id INTEGER,
	edad_agrupada_id INTEGER,
	escolaridad_id INTEGER,
	estado_civil_id INTEGER,
	ocupacion_id INTEGER,
	condicion_actividad_id INTEGER,
	nacionalidad_id INTEGER,
	lengua_indigena_id INTEGER,
	derechohabiencia_id INTEGER,
	area_urbana_rural_id INTEGER,
	asistencia_medica_id INTEGER,
	necropsia_id INTEGER,
	sitio_ocurrencia_id INTEGER,
	lugar_ocurrencia_id INTEGER,
	certificante_id INTEGER,
	presunta_defuncion_violenta_id INTEGER,
	ocurrio_trabajo_id INTEGER,
	violencia_familiar_id INTEGER,
	parentesco_agresor_id INTEGER,
	condicion_embarazo_id INTEGER,
	relacion_embarazo_id INTEGER,
	complicaron_embarazo_id INTEGER,
	razon_materna_id INTEGER,
	distrito_registro_oaxaca SMALLINT,
	fecha_actualizacion DATE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(edicion_id) REFERENCES cat_edicion (id),
	FOREIGN KEY(localidad_residencia_id) REFERENCES cat_localidad (id),
	FOREIGN KEY(localidad_ocurrencia_id) REFERENCES cat_localidad (id),
	FOREIGN KEY(localidad_lesion_id) REFERENCES cat_localidad (id),
	FOREIGN KEY(tamanio_localidad_residencia_id) REFERENCES cat_tamanio_localidad (id),
	FOREIGN KEY(tamanio_localidad_ocurrencia_id) REFERENCES cat_tamanio_localidad (id),
	FOREIGN KEY(causa_defuncion_id) REFERENCES cat_cie10 (id),
	FOREIGN KEY(causa_materna_id) REFERENCES cat_cie10 (id),
	FOREIGN KEY(capitulo_grupo_id) REFERENCES cat_capitulo_grupo (id),
	FOREIGN KEY(lista_cie_id) REFERENCES cat_lista_cie (id),
	FOREIGN KEY(lista_mexicana_id) REFERENCES cat_lista_mexicana (id),
	FOREIGN KEY(grupo_lista_mexicana_id) REFERENCES cat_grupo_lista_mexicana (id),
	FOREIGN KEY(sexo_id) REFERENCES cat_sexo (id),
	FOREIGN KEY(edad_agrupada_id) REFERENCES cat_edad_agrupada (id),
	FOREIGN KEY(escolaridad_id) REFERENCES cat_escolaridad (id),
	FOREIGN KEY(estado_civil_id) REFERENCES cat_estado_civil (id),
	FOREIGN KEY(ocupacion_id) REFERENCES cat_ocupacion (id),
	FOREIGN KEY(condicion_actividad_id) REFERENCES cat_condicion_actividad (id),
	FOREIGN KEY(nacionalidad_id) REFERENCES cat_nacionalidad (id),
	FOREIGN KEY(lengua_indigena_id) REFERENCES cat_lengua_indigena (id),
	FOREIGN KEY(derechohabiencia_id) REFERENCES cat_derechohabiencia (id),
	FOREIGN KEY(area_urbana_rural_id) REFERENCES cat_area_urbana_rural (id),
	FOREIGN KEY(asistencia_medica_id) REFERENCES cat_asistencia_medica (id),
	FOREIGN KEY(necropsia_id) REFERENCES cat_necropsia (id),
	FOREIGN KEY(sitio_ocurrencia_id) REFERENCES cat_sitio_ocurrencia (id),
	FOREIGN KEY(lugar_ocurrencia_id) REFERENCES cat_lugar_ocurrencia (id),
	FOREIGN KEY(certificante_id) REFERENCES cat_certificante (id),
	FOREIGN KEY(presunta_defuncion_violenta_id) REFERENCES cat_presunta_defuncion_violenta (id),
	FOREIGN KEY(ocurrio_trabajo_id) REFERENCES cat_ocurrio_trabajo (id),
	FOREIGN KEY(violencia_familiar_id) REFERENCES cat_violencia_familiar (id),
	FOREIGN KEY(parentesco_agresor_id) REFERENCES cat_parentesco_agresor (id),
	FOREIGN KEY(condicion_embarazo_id) REFERENCES cat_condicion_embarazo (id),
	FOREIGN KEY(relacion_embarazo_id) REFERENCES cat_relacion_embarazo (id),
	FOREIGN KEY(complicaron_embarazo_id) REFERENCES cat_complicaron_embarazo (id),
	FOREIGN KEY(razon_materna_id) REFERENCES cat_razon_materna (id)
);
CREATE INDEX ix_stg_defunciones_entidad_registro_id ON stg_defunciones (entidad_registro_id);
CREATE INDEX ix_stg_defunciones_edicion_id ON stg_defunciones (edicion_id);
CREATE INDEX ix_stg_defunciones_entidad_ocurrencia_id ON stg_defunciones (entidad_ocurrencia_id);
CREATE INDEX ix_stg_defunciones_entidad_lesion_id ON stg_defunciones (entidad_lesion_id);
CREATE INDEX ix_stg_defunciones_entidad_residencia_id ON stg_defunciones (entidad_residencia_id);

CREATE TABLE stg_defunciones_ampliacion (
	defuncion_id INTEGER NOT NULL,
	codigo_adicional_id INTEGER,
	entidad_nacimiento_id SMALLINT,
	pais_nacimiento_id INTEGER,
	pais_nacionalidad_id INTEGER,
	lengua_id INTEGER,
	localidad_registro_id INTEGER,
	tamanio_localidad_registro_id INTEGER,
	afromexicano_id INTEGER,
	condicion_indigena_id INTEGER,
	cirugia_id INTEGER,
	accidental_violenta_id INTEGER,
	uso_necropsia_id INTEGER,
	muerte_encefalica_id INTEGER,
	donador_id INTEGER,
	semanas_gestacion SMALLINT,
	peso_gramos SMALLINT,
	PRIMARY KEY (defuncion_id),
	FOREIGN KEY(defuncion_id) REFERENCES stg_defunciones (id),
	FOREIGN KEY(codigo_adicional_id) REFERENCES cat_cie10 (id),
	FOREIGN KEY(pais_nacimiento_id) REFERENCES cat_pais (id),
	FOREIGN KEY(pais_nacionalidad_id) REFERENCES cat_pais (id),
	FOREIGN KEY(lengua_id) REFERENCES cat_lengua (id),
	FOREIGN KEY(localidad_registro_id) REFERENCES cat_localidad (id),
	FOREIGN KEY(tamanio_localidad_registro_id) REFERENCES cat_tamanio_localidad (id),
	FOREIGN KEY(afromexicano_id) REFERENCES cat_afromexicano (id),
	FOREIGN KEY(condicion_indigena_id) REFERENCES cat_condicion_indigena (id),
	FOREIGN KEY(cirugia_id) REFERENCES cat_cirugia (id),
	FOREIGN KEY(accidental_violenta_id) REFERENCES cat_accidental_violenta (id),
	FOREIGN KEY(uso_necropsia_id) REFERENCES cat_uso_necropsia (id),
	FOREIGN KEY(muerte_encefalica_id) REFERENCES cat_muerte_encefalica (id),
	FOREIGN KEY(donador_id) REFERENCES cat_donador (id)
);
