-- COMMENT ON tomados del diccionario de datos oficial de INEGI (edición 2024).

COMMENT ON TABLE cat_accidental_violenta IS 'Catálogo de accidental violenta.';
COMMENT ON TABLE cat_afromexicano IS 'Catálogo de afromexicano.';
COMMENT ON TABLE cat_area_urbana_rural IS 'Catálogo de area urbana rural.';
COMMENT ON TABLE cat_asistencia_medica IS 'Catálogo de asistencia medica.';
COMMENT ON TABLE cat_capitulo_grupo IS 'Capítulos y grupos de causas detalladas CIE. Grupo nulo es el total del capítulo.';
COMMENT ON TABLE cat_certificante IS 'Catálogo de certificante.';
COMMENT ON TABLE cat_cirugia IS 'Catálogo de cirugia.';
COMMENT ON TABLE cat_complicaron_embarazo IS 'Catálogo de complicaron embarazo.';
COMMENT ON TABLE cat_condicion_actividad IS 'Catálogo de condicion actividad.';
COMMENT ON TABLE cat_condicion_embarazo IS 'Catálogo de condicion embarazo.';
COMMENT ON TABLE cat_condicion_indigena IS 'Catálogo de condicion indigena.';
COMMENT ON TABLE cat_donador IS 'Catálogo de donador.';
COMMENT ON TABLE cat_edad_agrupada IS 'Catálogo de edad agrupada.';
COMMENT ON TABLE cat_edicion IS 'Edición anual del programa EDR de la que proviene cada fila.';
COMMENT ON TABLE cat_escolaridad IS 'Catálogo de escolaridad.';
COMMENT ON TABLE cat_estado_civil IS 'Catálogo de estado civil.';
COMMENT ON TABLE cat_grupo_lista_mexicana IS 'Catálogo de grupo lista mexicana.';
COMMENT ON TABLE cat_lengua IS 'Catálogo de lengua.';
COMMENT ON TABLE cat_lengua_indigena IS 'Catálogo de lengua indigena.';
COMMENT ON TABLE cat_lista_cie IS 'Catálogo de lista cie.';
COMMENT ON TABLE cat_lista_mexicana IS 'Catálogo de lista mexicana.';
COMMENT ON TABLE cat_lugar_ocurrencia IS 'Catálogo de lugar ocurrencia.';
COMMENT ON TABLE cat_muerte_encefalica IS 'Catálogo de muerte encefalica.';
COMMENT ON TABLE cat_nacionalidad IS 'Catálogo de nacionalidad.';
COMMENT ON TABLE cat_necropsia IS 'Catálogo de necropsia.';
COMMENT ON TABLE cat_ocurrio_trabajo IS 'Catálogo de ocurrio trabajo.';
COMMENT ON TABLE cat_pais IS 'Países del catálogo de INEGI (claves 101-535). Las entidades federativas del mismo archivo se descartan por estar en cvegeo_states.';
COMMENT ON TABLE cat_parentesco_agresor IS 'Catálogo de parentesco agresor.';
COMMENT ON TABLE cat_presunta_defuncion_violenta IS 'Catálogo de presunta defuncion violenta.';
COMMENT ON TABLE cat_razon_materna IS 'Catálogo de razon materna.';
COMMENT ON TABLE cat_relacion_embarazo IS 'Catálogo de relacion embarazo.';
COMMENT ON TABLE cat_sexo IS 'Catálogo de sexo.';
COMMENT ON TABLE cat_sitio_ocurrencia IS 'Catálogo de sitio ocurrencia.';
COMMENT ON TABLE cat_tamanio_localidad IS 'Catálogo de tamanio localidad.';
COMMENT ON TABLE cat_uso_necropsia IS 'Catálogo de uso necropsia.';
COMMENT ON TABLE cat_violencia_familiar IS 'Catálogo de violencia familiar.';
COMMENT ON TABLE cat_cie10 IS 'Clasificación Internacional de Enfermedades, 10a revisión. Alimenta causa de defunción, código adicional y causa materna.';
COMMENT ON TABLE cat_derechohabiencia IS 'Catálogo de derechohabiencia.';
COMMENT ON TABLE cat_localidad IS 'Catálogo de localidades por edición. Entidades y municipios no se copian: viven en la base cvegeo y se consultan por FDW.';
COMMENT ON TABLE cat_ocupacion IS 'Catálogo de ocupacion.';
COMMENT ON TABLE stg_defunciones IS 'Defunciones registradas por INEGI (programa EDR). Una fila por defunción, con las variables presentes en todas las ediciones desde 2017.';
COMMENT ON TABLE stg_defunciones_ampliacion IS 'Variables que INEGI incorporó a partir de la edición 2022. Relación 1:1 con stg_defunciones; sin filas para ediciones anteriores.';

COMMENT ON COLUMN stg_defunciones.edicion_id IS 'Edición del programa EDR de la que proviene la fila.';
COMMENT ON COLUMN stg_defunciones.entidad_registro_id IS 'Entidad de registro';
COMMENT ON COLUMN stg_defunciones.municipio_registro_id IS 'Municipio o demarcación territorial de registro';
COMMENT ON COLUMN stg_defunciones.entidad_residencia_id IS 'Entidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.municipio_residencia_id IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.entidad_ocurrencia_id IS 'Entidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.municipio_ocurrencia_id IS 'Municipio o demarcación territorial de ocurrencia';
COMMENT ON COLUMN stg_defunciones.entidad_lesion_id IS 'Entidad de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.municipio_lesion_id IS 'Municipio o demarcación territorial de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.localidad_residencia_id IS 'Localidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.localidad_ocurrencia_id IS 'Localidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.localidad_lesion_id IS 'Localidad de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.tamanio_localidad_residencia_id IS 'Tamaño de localidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.tamanio_localidad_ocurrencia_id IS 'Tamaño de localidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.fecha_ocurrencia IS 'Fecha armada con dia_ocurr, mes_ocurr, anio_ocur de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN stg_defunciones.fecha_registro IS 'Fecha armada con dia_regis, mes_regis, anio_regis de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN stg_defunciones.fecha_nacimiento IS 'Fecha armada con dia_nacim, mes_nacim, anio_nacim de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN stg_defunciones.fecha_certificacion IS 'Fecha armada con dia_cert, mes_cert, anio_cert de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN stg_defunciones.hora_defuncion IS 'Hora de la defunción, armada con hora y minuto de la fuente.';
COMMENT ON COLUMN stg_defunciones.edad_cantidad IS 'Edad del fallecido, en la unidad que indica edad_unidad.';
COMMENT ON COLUMN stg_defunciones.edad_unidad IS 'Unidad de la edad: 1 horas, 2 días, 3 meses, 4 años.';
COMMENT ON COLUMN stg_defunciones.causa_defuncion_id IS 'Causa de la defunción (lista detallada)';
COMMENT ON COLUMN stg_defunciones.causa_materna_id IS 'Defunciones maternas totales';
COMMENT ON COLUMN stg_defunciones.lista_cie_id IS 'Lista de tabulación 1 para mortalidad de la CIE';
COMMENT ON COLUMN stg_defunciones.lista_mexicana_id IS 'Causa de la defunción (lista mexicana)';
COMMENT ON COLUMN stg_defunciones.grupo_lista_mexicana_id IS 'Lista mexicana de enfermedades (grupo)';
COMMENT ON COLUMN stg_defunciones.sexo_id IS 'Sexo del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.edad_agrupada_id IS 'Edad (agrupada) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.escolaridad_id IS 'Nivel de escolaridad del (la) fallecido (a) (escolaridad)';
COMMENT ON COLUMN stg_defunciones.estado_civil_id IS 'Estado conyugal (civil) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.ocupacion_id IS 'Ocupación del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.condicion_actividad_id IS 'Condición de actividad económica del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.nacionalidad_id IS 'Nacionalidad del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.lengua_indigena_id IS 'Condición de habla lengua indígena del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.derechohabiencia_id IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.area_urbana_rural_id IS 'Área urbana-rural de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.asistencia_medica_id IS 'Condición de atención médica';
COMMENT ON COLUMN stg_defunciones.necropsia_id IS 'Condición de necropsia';
COMMENT ON COLUMN stg_defunciones.sitio_ocurrencia_id IS 'Sitio de ocurrencia de la defunción';
COMMENT ON COLUMN stg_defunciones.lugar_ocurrencia_id IS 'Sitio de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.certificante_id IS 'Persona que certificó la defunción';
COMMENT ON COLUMN stg_defunciones.ocurrio_trabajo_id IS 'Ocurrió en el desempeño de su trabajo';
COMMENT ON COLUMN stg_defunciones.violencia_familiar_id IS 'Violencia familiar';
COMMENT ON COLUMN stg_defunciones.parentesco_agresor_id IS 'Parentesco del presunto agresor';
COMMENT ON COLUMN stg_defunciones.condicion_embarazo_id IS 'Condición de embarazo';
COMMENT ON COLUMN stg_defunciones.relacion_embarazo_id IS 'Causas relacionadas con el embarazo';
COMMENT ON COLUMN stg_defunciones.complicaron_embarazo_id IS 'Complicaron el embarazo';
COMMENT ON COLUMN stg_defunciones.razon_materna_id IS 'Defunciones para calcular la razón de la mortalidad materna';
COMMENT ON COLUMN stg_defunciones.distrito_registro_oaxaca IS 'Distritos de registro de Oaxaca';
COMMENT ON COLUMN stg_defunciones.fecha_actualizacion IS 'Fecha en que el pipeline cargó la fila.';

COMMENT ON COLUMN stg_defunciones_ampliacion.defuncion_id IS 'Defunción a la que amplía esta fila.';
COMMENT ON COLUMN stg_defunciones_ampliacion.codigo_adicional_id IS 'Código adicional CIE';
COMMENT ON COLUMN stg_defunciones_ampliacion.entidad_nacimiento_id IS 'Clave de la entidad federativa de nacimiento (001-032 del campo ent_nac).';
COMMENT ON COLUMN stg_defunciones_ampliacion.pais_nacimiento_id IS 'País de nacimiento (claves 101-535 del campo ent_nac).';
COMMENT ON COLUMN stg_defunciones_ampliacion.pais_nacionalidad_id IS 'Nacionalidad extranjera';
COMMENT ON COLUMN stg_defunciones_ampliacion.lengua_id IS 'Clave de la lengua indígena';
COMMENT ON COLUMN stg_defunciones_ampliacion.localidad_registro_id IS 'Localidad de registro';
COMMENT ON COLUMN stg_defunciones_ampliacion.tamanio_localidad_registro_id IS 'Tamaño de localidad de registro';
COMMENT ON COLUMN stg_defunciones_ampliacion.afromexicano_id IS 'Condición de autoadscripción como persona afromexicana';
COMMENT ON COLUMN stg_defunciones_ampliacion.condicion_indigena_id IS 'Condición de autoadscripción como persona indígena';
COMMENT ON COLUMN stg_defunciones_ampliacion.cirugia_id IS 'Condición de cirugía';
COMMENT ON COLUMN stg_defunciones_ampliacion.accidental_violenta_id IS 'La muerte fue accidental o violenta';
COMMENT ON COLUMN stg_defunciones_ampliacion.uso_necropsia_id IS 'Condición de uso de la necropsia';
COMMENT ON COLUMN stg_defunciones_ampliacion.muerte_encefalica_id IS 'Condición de muerte encefálica';
COMMENT ON COLUMN stg_defunciones_ampliacion.donador_id IS 'Condición de donador(a) de órganos';
COMMENT ON COLUMN stg_defunciones_ampliacion.semanas_gestacion IS 'Semanas de gestación de las personas fallecidas';
COMMENT ON COLUMN stg_defunciones_ampliacion.peso_gramos IS 'Peso en gramos de las personas fallecidas con menos de 28 días de edad';
