-- COMMENT ON de las vistas. Van aparte de V4 porque las vistas se crean en V5.
-- La columna legible lleva la descripción oficial de INEGI y su clave la misma
-- marcada como tal, siguiendo la convención X_id (clave) / X (descripción).

COMMENT ON VIEW vw_defunciones IS 'Defunciones registradas por INEGI con los catálogos resueltos a su descripción y la geografía a su nombre oficial. Convención: X_id es la clave (código INEGI o clave del catálogo) y X la descripción.';
COMMENT ON VIEW vw_defunciones_jalisco IS 'Igual que vw_defunciones, acotada a las defunciones en que Jalisco (entidad 14) aparece en cualquiera de los cuatro ámbitos: registro, residencia, ocurrencia u ocurrencia de la lesión.';
COMMENT ON VIEW vw_defunciones_ampliacion IS 'Variables que INEGI incorporó en 2022, con sus catálogos resueltos. Sólo tiene filas de la edición 2022 en adelante.';
COMMENT ON VIEW vw_defunciones_ampliacion_jalisco IS 'Igual que vw_defunciones_ampliacion, acotada a las defunciones en que Jalisco (entidad 14) aparece en cualquiera de los cuatro ámbitos.';

COMMENT ON COLUMN vw_defunciones.anio_edicion IS 'Año de la edición EDR de la que proviene la fila.';
COMMENT ON COLUMN vw_defunciones.entidad_registro_id IS 'Entidad de registro (clave).';
COMMENT ON COLUMN vw_defunciones.entidad_registro IS 'Entidad de registro.';
COMMENT ON COLUMN vw_defunciones.municipio_registro_id IS 'Municipio o demarcación territorial de registro (clave).';
COMMENT ON COLUMN vw_defunciones.municipio_registro IS 'Municipio o demarcación territorial de registro.';
COMMENT ON COLUMN vw_defunciones.entidad_residencia_id IS 'Entidad de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones.entidad_residencia IS 'Entidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.municipio_residencia_id IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones.municipio_residencia IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.localidad_residencia_id IS 'Localidad de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones.localidad_residencia IS 'Localidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.entidad_ocurrencia_id IS 'Entidad de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones.entidad_ocurrencia IS 'Entidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones.municipio_ocurrencia_id IS 'Municipio o demarcación territorial de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones.municipio_ocurrencia IS 'Municipio o demarcación territorial de ocurrencia.';
COMMENT ON COLUMN vw_defunciones.localidad_ocurrencia_id IS 'Localidad de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones.localidad_ocurrencia IS 'Localidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones.entidad_lesion_id IS 'Entidad de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones.entidad_lesion IS 'Entidad de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones.municipio_lesion_id IS 'Municipio o demarcación territorial de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones.municipio_lesion IS 'Municipio o demarcación territorial de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones.localidad_lesion_id IS 'Localidad de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones.localidad_lesion IS 'Localidad de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones.fecha_ocurrencia IS 'Fecha armada con dia_ocurr, mes_ocurr, anio_ocur de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones.fecha_registro IS 'Fecha armada con dia_regis, mes_regis, anio_regis de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones.fecha_nacimiento IS 'Fecha armada con dia_nacim, mes_nacim, anio_nacim de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones.fecha_certificacion IS 'Fecha armada con dia_cert, mes_cert, anio_cert de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones.hora_defuncion IS 'Hora de la defunción, armada con hora y minuto de la fuente.';
COMMENT ON COLUMN vw_defunciones.edad_cantidad IS 'Edad del fallecido, en la unidad que indica edad_unidad.';
COMMENT ON COLUMN vw_defunciones.edad_unidad IS 'Unidad de la edad: 1 horas, 2 días, 3 meses, 4 años.';
COMMENT ON COLUMN vw_defunciones.distrito_registro_oaxaca IS 'Distritos de registro de Oaxaca.';
COMMENT ON COLUMN vw_defunciones.fecha_actualizacion IS 'Fecha en que el pipeline cargó la fila.';
COMMENT ON COLUMN vw_defunciones.capitulo IS 'Capítulo de causas detalladas CIE.';
COMMENT ON COLUMN vw_defunciones.grupo IS 'Grupo de causas detalladas CIE; nulo cuando la fila es el total del capítulo.';
COMMENT ON COLUMN vw_defunciones.capitulo_grupo IS 'Descripción del capítulo y grupo de causas detalladas CIE.';
COMMENT ON COLUMN vw_defunciones.sexo IS 'Sexo del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.edad_agrupada IS 'Edad (agrupada) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.escolaridad IS 'Nivel de escolaridad del (la) fallecido (a) (escolaridad).';
COMMENT ON COLUMN vw_defunciones.estado_civil IS 'Estado conyugal (civil) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.condicion_actividad IS 'Condición de actividad económica del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.nacionalidad IS 'Nacionalidad del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.lengua_indigena IS 'Condición de habla lengua indígena del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.area_urbana_rural IS 'Área urbana-rural de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.asistencia_medica IS 'Condición de atención médica.';
COMMENT ON COLUMN vw_defunciones.necropsia IS 'Condición de necropsia.';
COMMENT ON COLUMN vw_defunciones.sitio_ocurrencia IS 'Sitio de ocurrencia de la defunción.';
COMMENT ON COLUMN vw_defunciones.lugar_ocurrencia IS 'Sitio de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones.certificante IS 'Persona que certificó la defunción.';
COMMENT ON COLUMN vw_defunciones.ocurrio_trabajo IS 'Ocurrió en el desempeño de su trabajo.';
COMMENT ON COLUMN vw_defunciones.violencia_familiar IS 'Violencia familiar.';
COMMENT ON COLUMN vw_defunciones.parentesco_agresor IS 'Parentesco del presunto agresor.';
COMMENT ON COLUMN vw_defunciones.condicion_embarazo IS 'Condición de embarazo.';
COMMENT ON COLUMN vw_defunciones.relacion_embarazo IS 'Causas relacionadas con el embarazo.';
COMMENT ON COLUMN vw_defunciones.complicaron_embarazo IS 'Complicaron el embarazo.';
COMMENT ON COLUMN vw_defunciones.razon_materna IS 'Defunciones para calcular la razón de la mortalidad materna.';
COMMENT ON COLUMN vw_defunciones.lista_cie IS 'Lista de tabulación 1 para mortalidad de la CIE.';
COMMENT ON COLUMN vw_defunciones.lista_mexicana IS 'Causa de la defunción (lista mexicana).';
COMMENT ON COLUMN vw_defunciones.grupo_lista_mexicana IS 'Lista mexicana de enfermedades (grupo).';
COMMENT ON COLUMN vw_defunciones.tamanio_localidad_residencia IS 'Tamaño de localidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.tamanio_localidad_ocurrencia IS 'Tamaño de localidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones.ocupacion_id IS 'Ocupación del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones.ocupacion IS 'Ocupación del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.derechohabiencia_id IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones.derechohabiencia IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones.causa_defuncion_id IS 'Causa de la defunción (lista detallada) (clave).';
COMMENT ON COLUMN vw_defunciones.causa_defuncion IS 'Causa de la defunción (lista detallada).';
COMMENT ON COLUMN vw_defunciones.causa_materna_id IS 'Defunciones maternas totales (clave).';
COMMENT ON COLUMN vw_defunciones.causa_materna IS 'Defunciones maternas totales.';

COMMENT ON COLUMN vw_defunciones_jalisco.anio_edicion IS 'Año de la edición EDR de la que proviene la fila.';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_registro_id IS 'Entidad de registro (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_registro IS 'Entidad de registro.';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_registro_id IS 'Municipio o demarcación territorial de registro (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_registro IS 'Municipio o demarcación territorial de registro.';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_residencia_id IS 'Entidad de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_residencia IS 'Entidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_residencia_id IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_residencia IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_residencia_id IS 'Localidad de residencia habitual del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_residencia IS 'Localidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_ocurrencia_id IS 'Entidad de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_ocurrencia IS 'Entidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_ocurrencia_id IS 'Municipio o demarcación territorial de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_ocurrencia IS 'Municipio o demarcación territorial de ocurrencia.';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_ocurrencia_id IS 'Localidad de ocurrencia (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_ocurrencia IS 'Localidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_lesion_id IS 'Entidad de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.entidad_lesion IS 'Entidad de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_lesion_id IS 'Municipio o demarcación territorial de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.municipio_lesion IS 'Municipio o demarcación territorial de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_lesion_id IS 'Localidad de ocurrencia de la lesión (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.localidad_lesion IS 'Localidad de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones_jalisco.fecha_ocurrencia IS 'Fecha armada con dia_ocurr, mes_ocurr, anio_ocur de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones_jalisco.fecha_registro IS 'Fecha armada con dia_regis, mes_regis, anio_regis de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones_jalisco.fecha_nacimiento IS 'Fecha armada con dia_nacim, mes_nacim, anio_nacim de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones_jalisco.fecha_certificacion IS 'Fecha armada con dia_cert, mes_cert, anio_cert de la fuente; nula si algún componente es centinela.';
COMMENT ON COLUMN vw_defunciones_jalisco.hora_defuncion IS 'Hora de la defunción, armada con hora y minuto de la fuente.';
COMMENT ON COLUMN vw_defunciones_jalisco.edad_cantidad IS 'Edad del fallecido, en la unidad que indica edad_unidad.';
COMMENT ON COLUMN vw_defunciones_jalisco.edad_unidad IS 'Unidad de la edad: 1 horas, 2 días, 3 meses, 4 años.';
COMMENT ON COLUMN vw_defunciones_jalisco.distrito_registro_oaxaca IS 'Distritos de registro de Oaxaca.';
COMMENT ON COLUMN vw_defunciones_jalisco.fecha_actualizacion IS 'Fecha en que el pipeline cargó la fila.';
COMMENT ON COLUMN vw_defunciones_jalisco.capitulo IS 'Capítulo de causas detalladas CIE.';
COMMENT ON COLUMN vw_defunciones_jalisco.grupo IS 'Grupo de causas detalladas CIE; nulo cuando la fila es el total del capítulo.';
COMMENT ON COLUMN vw_defunciones_jalisco.capitulo_grupo IS 'Descripción del capítulo y grupo de causas detalladas CIE.';
COMMENT ON COLUMN vw_defunciones_jalisco.sexo IS 'Sexo del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.edad_agrupada IS 'Edad (agrupada) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.escolaridad IS 'Nivel de escolaridad del (la) fallecido (a) (escolaridad).';
COMMENT ON COLUMN vw_defunciones_jalisco.estado_civil IS 'Estado conyugal (civil) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.condicion_actividad IS 'Condición de actividad económica del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.nacionalidad IS 'Nacionalidad del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.lengua_indigena IS 'Condición de habla lengua indígena del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.area_urbana_rural IS 'Área urbana-rural de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.asistencia_medica IS 'Condición de atención médica.';
COMMENT ON COLUMN vw_defunciones_jalisco.necropsia IS 'Condición de necropsia.';
COMMENT ON COLUMN vw_defunciones_jalisco.sitio_ocurrencia IS 'Sitio de ocurrencia de la defunción.';
COMMENT ON COLUMN vw_defunciones_jalisco.lugar_ocurrencia IS 'Sitio de ocurrencia de la lesión.';
COMMENT ON COLUMN vw_defunciones_jalisco.certificante IS 'Persona que certificó la defunción.';
COMMENT ON COLUMN vw_defunciones_jalisco.ocurrio_trabajo IS 'Ocurrió en el desempeño de su trabajo.';
COMMENT ON COLUMN vw_defunciones_jalisco.violencia_familiar IS 'Violencia familiar.';
COMMENT ON COLUMN vw_defunciones_jalisco.parentesco_agresor IS 'Parentesco del presunto agresor.';
COMMENT ON COLUMN vw_defunciones_jalisco.condicion_embarazo IS 'Condición de embarazo.';
COMMENT ON COLUMN vw_defunciones_jalisco.relacion_embarazo IS 'Causas relacionadas con el embarazo.';
COMMENT ON COLUMN vw_defunciones_jalisco.complicaron_embarazo IS 'Complicaron el embarazo.';
COMMENT ON COLUMN vw_defunciones_jalisco.razon_materna IS 'Defunciones para calcular la razón de la mortalidad materna.';
COMMENT ON COLUMN vw_defunciones_jalisco.lista_cie IS 'Lista de tabulación 1 para mortalidad de la CIE.';
COMMENT ON COLUMN vw_defunciones_jalisco.lista_mexicana IS 'Causa de la defunción (lista mexicana).';
COMMENT ON COLUMN vw_defunciones_jalisco.grupo_lista_mexicana IS 'Lista mexicana de enfermedades (grupo).';
COMMENT ON COLUMN vw_defunciones_jalisco.tamanio_localidad_residencia IS 'Tamaño de localidad de residencia habitual del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.tamanio_localidad_ocurrencia IS 'Tamaño de localidad de ocurrencia.';
COMMENT ON COLUMN vw_defunciones_jalisco.ocupacion_id IS 'Ocupación del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.ocupacion IS 'Ocupación del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.derechohabiencia_id IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.derechohabiencia IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a).';
COMMENT ON COLUMN vw_defunciones_jalisco.causa_defuncion_id IS 'Causa de la defunción (lista detallada) (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.causa_defuncion IS 'Causa de la defunción (lista detallada).';
COMMENT ON COLUMN vw_defunciones_jalisco.causa_materna_id IS 'Defunciones maternas totales (clave).';
COMMENT ON COLUMN vw_defunciones_jalisco.causa_materna IS 'Defunciones maternas totales.';

COMMENT ON COLUMN vw_defunciones_ampliacion.defuncion_id IS 'Defunción a la que amplía esta fila.';
COMMENT ON COLUMN vw_defunciones_ampliacion.anio_edicion IS 'Año de la edición EDR de la que proviene la fila.';
COMMENT ON COLUMN vw_defunciones_ampliacion.entidad_nacimiento_id IS 'Clave de la entidad federativa de nacimiento (001-032 del campo ent_nac) (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion.entidad_nacimiento IS 'Clave de la entidad federativa de nacimiento (001-032 del campo ent_nac).';
COMMENT ON COLUMN vw_defunciones_ampliacion.pais_nacimiento_id IS 'País de nacimiento (claves 101-535 del campo ent_nac) (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion.pais_nacimiento IS 'País de nacimiento (claves 101-535 del campo ent_nac).';
COMMENT ON COLUMN vw_defunciones_ampliacion.pais_nacionalidad_id IS 'Nacionalidad extranjera (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion.pais_nacionalidad IS 'Nacionalidad extranjera.';
COMMENT ON COLUMN vw_defunciones_ampliacion.localidad_registro_id IS 'Localidad de registro (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion.localidad_registro IS 'Localidad de registro.';
COMMENT ON COLUMN vw_defunciones_ampliacion.semanas_gestacion IS 'Semanas de gestación de las personas fallecidas.';
COMMENT ON COLUMN vw_defunciones_ampliacion.peso_gramos IS 'Peso en gramos de las personas fallecidas con menos de 28 días de edad.';
COMMENT ON COLUMN vw_defunciones_ampliacion.tamanio_localidad_registro IS 'Tamaño de localidad de registro.';
COMMENT ON COLUMN vw_defunciones_ampliacion.afromexicano IS 'Condición de autoadscripción como persona afromexicana.';
COMMENT ON COLUMN vw_defunciones_ampliacion.condicion_indigena IS 'Condición de autoadscripción como persona indígena.';
COMMENT ON COLUMN vw_defunciones_ampliacion.lengua IS 'Clave de la lengua indígena.';
COMMENT ON COLUMN vw_defunciones_ampliacion.cirugia IS 'Condición de cirugía.';
COMMENT ON COLUMN vw_defunciones_ampliacion.accidental_violenta IS 'La muerte fue accidental o violenta.';
COMMENT ON COLUMN vw_defunciones_ampliacion.uso_necropsia IS 'Condición de uso de la necropsia.';
COMMENT ON COLUMN vw_defunciones_ampliacion.muerte_encefalica IS 'Condición de muerte encefálica.';
COMMENT ON COLUMN vw_defunciones_ampliacion.donador IS 'Condición de donador(a) de órganos.';
COMMENT ON COLUMN vw_defunciones_ampliacion.codigo_adicional_id IS 'Código adicional CIE (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion.codigo_adicional IS 'Código adicional CIE.';

COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.defuncion_id IS 'Defunción a la que amplía esta fila.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.anio_edicion IS 'Año de la edición EDR de la que proviene la fila.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.entidad_nacimiento_id IS 'Clave de la entidad federativa de nacimiento (001-032 del campo ent_nac) (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.entidad_nacimiento IS 'Clave de la entidad federativa de nacimiento (001-032 del campo ent_nac).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.pais_nacimiento_id IS 'País de nacimiento (claves 101-535 del campo ent_nac) (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.pais_nacimiento IS 'País de nacimiento (claves 101-535 del campo ent_nac).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.pais_nacionalidad_id IS 'Nacionalidad extranjera (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.pais_nacionalidad IS 'Nacionalidad extranjera.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.localidad_registro_id IS 'Localidad de registro (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.localidad_registro IS 'Localidad de registro.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.semanas_gestacion IS 'Semanas de gestación de las personas fallecidas.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.peso_gramos IS 'Peso en gramos de las personas fallecidas con menos de 28 días de edad.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.tamanio_localidad_registro IS 'Tamaño de localidad de registro.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.afromexicano IS 'Condición de autoadscripción como persona afromexicana.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.condicion_indigena IS 'Condición de autoadscripción como persona indígena.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.lengua IS 'Clave de la lengua indígena.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.cirugia IS 'Condición de cirugía.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.accidental_violenta IS 'La muerte fue accidental o violenta.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.uso_necropsia IS 'Condición de uso de la necropsia.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.muerte_encefalica IS 'Condición de muerte encefálica.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.donador IS 'Condición de donador(a) de órganos.';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.codigo_adicional_id IS 'Código adicional CIE (clave).';
COMMENT ON COLUMN vw_defunciones_ampliacion_jalisco.codigo_adicional IS 'Código adicional CIE.';
