CREATE TABLE IF NOT EXISTS stg_enoe_microdatos (
    id                      SERIAL PRIMARY KEY,
    anio                    SMALLINT    NOT NULL,
    trimestre               SMALLINT    NOT NULL,
    -- SDEM: diseño muestral
    r_def                   SMALLINT,
    est                     SMALLINT,
    est_d_tri               SMALLINT,
    est_d_men               SMALLINT,
    ageb                    SMALLINT,
    upm                     INTEGER,
    d_sem                   SMALLINT,
    n_pro_viv               SMALLINT,
    per                     SMALLINT,
    tipo                    SMALLINT,
    mes_cal                 SMALLINT,
    -- SDEM: identificadores de persona (clave natural)
    cd_a                    SMALLINT    NOT NULL,
    entidad_id              SMALLINT    NOT NULL,
    con                     INTEGER     NOT NULL,
    v_sel                   SMALLINT    NOT NULL,
    n_hog                   SMALLINT    NOT NULL,
    h_mud                   SMALLINT    NOT NULL,
    n_ent                   SMALLINT    NOT NULL,
    n_ren                   SMALLINT    NOT NULL,
    -- SDEM: geografía
    loc                     TEXT,
    municipio_id            SMALLINT,
    tipo_localidad_id       SMALLINT,
    t_loc_men               SMALLINT,
    ur                      SMALLINT,
    zona                    SMALLINT,
    -- SDEM: sociodemográfico
    c_res                   SMALLINT,
    par_c                   SMALLINT,
    sex                     SMALLINT,
    eda                     SMALLINT,
    nac_dia                 SMALLINT,
    nac_mes                 SMALLINT,
    nac_anio                SMALLINT,
    l_nac_c                 SMALLINT,
    -- SDEM: educación
    cs_p12                  SMALLINT,
    cs_p13_1                SMALLINT,
    cs_p13_2                SMALLINT,
    cs_p14_c                INTEGER,
    cs_p15                  SMALLINT,
    cs_p16                  SMALLINT,
    cs_p17                  SMALLINT,
    niv_ins                 SMALLINT,
    anios_esc               SMALLINT,
    -- SDEM: hijos
    n_hij                   SMALLINT,
    hij5c                   SMALLINT,
    -- SDEM: estado civil
    e_con                   SMALLINT,
    -- SDEM: migración
    cs_p20a_1               SMALLINT,
    cs_p20a_c               SMALLINT,
    cs_p20b_1               SMALLINT,
    cs_p20b_c               SMALLINT,
    cs_p20c_1               SMALLINT,
    cs_ad_mot               SMALLINT,
    cs_p21_des              TEXT,
    cs_ad_des               SMALLINT,
    cs_nr_mot               SMALLINT,
    cs_p23_des              TEXT,
    cs_nr_ori               SMALLINT,
    -- SDEM: clasificación de actividad
    clase1                  SMALLINT,
    clase2                  SMALLINT,
    clase3                  SMALLINT,
    seg_soc                 SMALLINT,
    rama                    SMALLINT,
    rama_est2               SMALLINT,
    ing7c                   SMALLINT,
    dur9c                   SMALLINT,
    emple7c                 SMALLINT,
    medica5c                SMALLINT,
    buscar5c                SMALLINT,
    dur_est                 SMALLINT,
    ambito1                 SMALLINT,
    ambito2                 SMALLINT,
    scian                   SMALLINT,
    -- SDEM: búsqueda y disponibilidad
    dispo                   SMALLINT,
    nodispo                 SMALLINT,
    c_inac5c                SMALLINT,
    pnea_est                SMALLINT,
    busqueda                SMALLINT,
    d_ant_lab               SMALLINT,
    d_cexp_est              SMALLINT,
    dur_des                 SMALLINT,
    -- SDEM: informalidad (TIL1)
    tue1                    SMALLINT,
    tue2                    SMALLINT,
    tue3                    SMALLINT,
    tue_ppal                SMALLINT,
    emp_ppal                SMALLINT,
    trans_ppal              SMALLINT,
    sub_o                   SMALLINT,
    s_clasifi               SMALLINT,
    remune2c                SMALLINT,
    pre_asa                 SMALLINT,
    tip_con                 SMALLINT,
    sec_ins                 SMALLINT,
    mh_fil2                 SMALLINT,
    mh_col                  SMALLINT,
    t_tra                   SMALLINT,
    -- SDEM: trabajo doméstico y edades derivadas
    domestico               SMALLINT,
    eda5c                   SMALLINT,
    eda7c                   SMALLINT,
    eda12c                  SMALLINT,
    eda19c                  SMALLINT,
    -- SDEM: horas e ingresos
    hrsocup                 SMALLINT,
    ingocup                 INTEGER,
    ing_x_hrs               FLOAT,
    salario                 INTEGER,
    -- SDEM: tasas y complementos
    tpg_p8a                 SMALLINT,
    tcco                    SMALLINT,
    cp_anoc                 SMALLINT,
    imssissste              SMALLINT,
    ma48me1sm               SMALLINT,
    p14apoyos               SMALLINT,
    -- SDEM: factor de expansión
    fac                     INTEGER,
    fac_men                 INTEGER,
    -- FKs a catálogos
    sector_id               SMALLINT    REFERENCES cat_enoe_sector (id),
    ocupacion_id            SMALLINT    REFERENCES cat_enoe_ocupacion (id),
    situacion_trabajo_id    SMALLINT    REFERENCES cat_enoe_situacion_trabajo (id),
    -- De COE1
    p3b                     SMALLINT,
    p3i                     SMALLINT,
    -- De COE2
    p10b                    SMALLINT,
    -- Indicadores derivados
    es_pea                  BOOLEAN,
    es_ocupado              BOOLEAN,
    es_desocupado           BOOLEAN,
    es_informal             BOOLEAN,

    CONSTRAINT uq_stg_enoe_microdatos_persona
        UNIQUE (anio, trimestre, cd_a, entidad_id, con, v_sel, n_hog, h_mud, n_ent, n_ren)
);
