CREATE UNLOGGED TABLE IF NOT EXISTS stg_establecimientos (
    id INTEGER NOT NULL,
    actualizacion_id INTEGER NOT NULL REFERENCES cat_actualizaciones(id),
    nombre_establecimiento TEXT NOT NULL,
    razon_social TEXT,
    latitud FLOAT,
    longitud FLOAT,
    fecha_alta DATE,
    nombre_asentamiento TEXT,
    ageb TEXT,
    localidad_id INTEGER REFERENCES cat_localidades(id),
    sector_id INTEGER REFERENCES cat_sectores(id),
    subsector_id INTEGER REFERENCES cat_subsectores(id),
    rama_id INTEGER REFERENCES cat_ramas(id),
    subrama_id INTEGER REFERENCES cat_subramas(id),
    clase_actividad_id INTEGER REFERENCES cat_clases_actividad(id),
    rango_personal_id INTEGER REFERENCES cat_rangos_personal(id),
    tipo_establecimiento_id INTEGER REFERENCES cat_tipos_establecimientos(id),
    PRIMARY KEY (id, actualizacion_id)
);
