CREATE TABLE IF NOT EXISTS stg_directorio_escuelas (
    id SERIAL PRIMARY KEY,
    anio INTEGER NOT NULL,
    entidad_id INTEGER NOT NULL,
    clave_ct VARCHAR(20) NOT NULL,
    turno_id INTEGER NOT NULL REFERENCES cat_turnos(id),
    nombre_ct VARCHAR(255) NOT NULL,
    domicilio TEXT,
    localidad_id INTEGER,
    nombre_localidad VARCHAR(150),
    colonia_id INTEGER,
    nombre_colonia VARCHAR(150),
    municipio_id INTEGER NOT NULL,
    nombre_municipio VARCHAR(150),
    medio_id INTEGER REFERENCES cat_medios(id),
    director VARCHAR(255),
    codigo_postal VARCHAR(10),
    telefono VARCHAR(20),
    zona_escolar INTEGER,
    sector INTEGER,
    codigo_sostenimiento_id INTEGER REFERENCES cat_codigos_sostenimiento(id),
    nivel_id INTEGER NOT NULL REFERENCES cat_niveles(id),
    programa_id INTEGER NOT NULL REFERENCES cat_programas(id),
    region_id INTEGER REFERENCES cat_regiones(id),
    longitud FLOAT,
    latitud FLOAT,
    escuelas INTEGER NOT NULL,
    hombres_matriculados INTEGER NOT NULL,
    mujeres_matriculadas INTEGER NOT NULL,
    total_matriculados INTEGER NOT NULL,
    total_docentes_directivo INTEGER NOT NULL,
    fecha_actualizacion DATE NOT NULL,
    CONSTRAINT uq_stg_directorio_escuelas UNIQUE (anio, clave_ct, turno_id, nivel_id, programa_id)
);

CREATE TABLE IF NOT EXISTS stg_estadistica_escuelas (
    id SERIAL PRIMARY KEY,
    anio INTEGER NOT NULL,
    nivel_programa_id INTEGER NOT NULL REFERENCES cat_niveles_programa(id),
    sostenimiento_id INTEGER NOT NULL REFERENCES cat_sostenimientos(id),
    escuelas INTEGER NOT NULL,
    matricula INTEGER NOT NULL,
    docentes INTEGER NOT NULL,
    fecha_actualizacion DATE NOT NULL,
    CONSTRAINT uq_stg_estadistica_escuelas UNIQUE (anio, nivel_programa_id, sostenimiento_id)
);
