CREATE TABLE IF NOT EXISTS stg_poblacion_mitad_anio (
    id SERIAL PRIMARY KEY,
    municipio_id INTEGER NOT NULL,
    entidad_id INTEGER NOT NULL,
    sexo_id INTEGER NOT NULL REFERENCES cat_sexo(id),
    anio INTEGER NOT NULL,
    pob_00_04 INTEGER,
    pob_05_09 INTEGER,
    pob_10_14 INTEGER,
    pob_15_19 INTEGER,
    pob_20_24 INTEGER,
    pob_25_29 INTEGER,
    pob_30_34 INTEGER,
    pob_35_39 INTEGER,
    pob_40_44 INTEGER,
    pob_45_49 INTEGER,
    pob_50_54 INTEGER,
    pob_55_59 INTEGER,
    pob_60_64 INTEGER,
    pob_65_69 INTEGER,
    pob_70_74 INTEGER,
    pob_75_79 INTEGER,
    pob_80_84 INTEGER,
    pob_85_mm INTEGER,
    pob_total INTEGER,
    fecha_actualizacion DATE NOT NULL,
    CONSTRAINT uq_pma_mun_sexo_anio UNIQUE (municipio_id, sexo_id, anio)
);

CREATE TABLE IF NOT EXISTS stg_grandes_grupos_edad (
    id SERIAL PRIMARY KEY,
    municipio_id INTEGER NOT NULL,
    entidad_id INTEGER NOT NULL,
    sexo_id INTEGER NOT NULL REFERENCES cat_sexo(id),
    anio INTEGER NOT NULL,
    pob_00_11 INTEGER,
    pob_12_29 INTEGER,
    pob_30_59 INTEGER,
    pob_60_mm INTEGER,
    pob_total INTEGER,
    fecha_actualizacion DATE NOT NULL,
    CONSTRAINT uq_gge_mun_sexo_anio UNIQUE (municipio_id, sexo_id, anio)
);

CREATE TABLE IF NOT EXISTS stg_indicadores_demograficos (
    id SERIAL PRIMARY KEY,
    municipio_id INTEGER NOT NULL,
    entidad_id INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    hom_mit_ano INTEGER,
    muj_mit_ano INTEGER,
    pob_mit_mun INTEGER,
    muj_00_14 INTEGER,
    hom_00_14 INTEGER,
    pob_00_14 INTEGER,
    muj_15_64 INTEGER,
    hom_15_64 INTEGER,
    pob_15_64 INTEGER,
    muj_60_mas INTEGER,
    hom_60_mas INTEGER,
    pob_60_mas INTEGER,
    muj_65_mas INTEGER,
    hom_65_mas INTEGER,
    pob_65_mas INTEGER,
    pob_mit_ent INTEGER,
    edad_med INTEGER,
    por_mun FLOAT,
    ind_env_60 FLOAT,
    ind_env_65 FLOAT,
    rhm FLOAT,
    raz_dep_adu FLOAT,
    raz_dep_inf FLOAT,
    raz_dep FLOAT,
    fecha_actualizacion DATE NOT NULL,
    CONSTRAINT uq_idd_mun_anio UNIQUE (municipio_id, anio)
);
