COMMENT ON TABLE cat_sexo IS 'Catálogo de sexo para clasificar datos demográficos. Contiene las categorías HOMBRES y MUJERES utilizadas en las proyecciones de población de CONAPO.';
COMMENT ON COLUMN cat_sexo.id IS 'Identificador único del sexo (1 = HOMBRES, 2 = MUJERES).';
COMMENT ON COLUMN cat_sexo.sexo IS 'Nombre del sexo (HOMBRES o MUJERES).';

COMMENT ON TABLE stg_poblacion_mitad_anio IS 'Tabla de staging que contiene proyecciones de población a mitad de año por grupo quinquenal de edad, sexo, municipio y año. Datos de CONAPO para Jalisco, periodo 1990-2040. Cada registro representa la población de un grupo de edad específico para un municipio, sexo y año.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.id IS 'Identificador único autogenerado para cada registro.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.municipio_id IS 'Clave única del municipio (cvegeo). Referencia implícita a cvegeo_municipalities.cvegeo.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.entidad_id IS 'Clave de la entidad federativa (cve_ent). Jalisco = 14. Referencia implícita a cvegeo_states.cve_ent.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.sexo_id IS 'Referencia al sexo (FK a cat_sexo).';
COMMENT ON COLUMN stg_poblacion_mitad_anio.anio IS 'Año de la proyección (1990-2040).';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_00_04 IS 'Población de 0 a 4 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_05_09 IS 'Población de 5 a 9 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_10_14 IS 'Población de 10 a 14 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_15_19 IS 'Población de 15 a 19 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_20_24 IS 'Población de 20 a 24 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_25_29 IS 'Población de 25 a 29 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_30_34 IS 'Población de 30 a 34 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_35_39 IS 'Población de 35 a 39 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_40_44 IS 'Población de 40 a 44 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_45_49 IS 'Población de 45 a 49 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_50_54 IS 'Población de 50 a 54 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_55_59 IS 'Población de 55 a 59 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_60_64 IS 'Población de 60 a 64 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_65_69 IS 'Población de 65 a 69 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_70_74 IS 'Población de 70 a 74 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_75_79 IS 'Población de 75 a 79 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_80_84 IS 'Población de 80 a 84 años.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_85_mm IS 'Población de 85 años y más.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.pob_total IS 'Población total del municipio para ese sexo y año.';
COMMENT ON COLUMN stg_poblacion_mitad_anio.fecha_actualizacion IS 'Fecha de actualización del registro.';

COMMENT ON TABLE stg_grandes_grupos_edad IS 'Tabla de staging que contiene proyecciones de población por grandes grupos de edad, sexo, municipio y año. Datos de CONAPO para Jalisco, periodo 1990-2040. Los grupos son: 0-11, 12-29, 30-59, 60 y más.';
COMMENT ON COLUMN stg_grandes_grupos_edad.id IS 'Identificador único autogenerado para cada registro.';
COMMENT ON COLUMN stg_grandes_grupos_edad.municipio_id IS 'Clave única del municipio (cvegeo). Referencia implícita a cvegeo_municipalities.cvegeo.';
COMMENT ON COLUMN stg_grandes_grupos_edad.entidad_id IS 'Clave de la entidad federativa (cve_ent). Jalisco = 14. Referencia implícita a cvegeo_states.cve_ent.';
COMMENT ON COLUMN stg_grandes_grupos_edad.sexo_id IS 'Referencia al sexo (FK a cat_sexo).';
COMMENT ON COLUMN stg_grandes_grupos_edad.anio IS 'Año de la proyección (1990-2040).';
COMMENT ON COLUMN stg_grandes_grupos_edad.pob_00_11 IS 'Población de 0 a 11 años (infancia).';
COMMENT ON COLUMN stg_grandes_grupos_edad.pob_12_29 IS 'Población de 12 a 29 años (juventud).';
COMMENT ON COLUMN stg_grandes_grupos_edad.pob_30_59 IS 'Población de 30 a 59 años (adultos en edad productiva).';
COMMENT ON COLUMN stg_grandes_grupos_edad.pob_60_mm IS 'Población de 60 años y más (adultos mayores).';
COMMENT ON COLUMN stg_grandes_grupos_edad.pob_total IS 'Población total del municipio para ese sexo y año.';
COMMENT ON COLUMN stg_grandes_grupos_edad.fecha_actualizacion IS 'Fecha de actualización del registro.';

COMMENT ON TABLE stg_indicadores_demograficos IS 'Tabla de staging que contiene indicadores demográficos diversos por municipio y año. Datos de CONAPO para Jalisco, periodo 1990-2040. Incluye razones de dependencia, edad mediana, índices de envejecimiento y otros indicadores.';
COMMENT ON COLUMN stg_indicadores_demograficos.id IS 'Identificador único autogenerado para cada registro.';
COMMENT ON COLUMN stg_indicadores_demograficos.municipio_id IS 'Clave única del municipio (cvegeo). Referencia implícita a cvegeo_municipalities.cvegeo.';
COMMENT ON COLUMN stg_indicadores_demograficos.entidad_id IS 'Clave de la entidad federativa (cve_ent). Jalisco = 14. Referencia implícita a cvegeo_states.cve_ent.';
COMMENT ON COLUMN stg_indicadores_demograficos.anio IS 'Año del indicador (1990-2040).';
COMMENT ON COLUMN stg_indicadores_demograficos.hom_mit_ano IS 'Población masculina a mitad de año.';
COMMENT ON COLUMN stg_indicadores_demograficos.muj_mit_ano IS 'Población femenina a mitad de año.';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_mit_mun IS 'Población total del municipio a mitad de año.';
COMMENT ON COLUMN stg_indicadores_demograficos.muj_00_14 IS 'Población femenina de 0 a 14 años.';
COMMENT ON COLUMN stg_indicadores_demograficos.hom_00_14 IS 'Población masculina de 0 a 14 años.';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_00_14 IS 'Población total de 0 a 14 años.';
COMMENT ON COLUMN stg_indicadores_demograficos.muj_15_64 IS 'Población femenina de 15 a 64 años (edad productiva).';
COMMENT ON COLUMN stg_indicadores_demograficos.hom_15_64 IS 'Población masculina de 15 a 64 años (edad productiva).';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_15_64 IS 'Población total de 15 a 64 años (edad productiva).';
COMMENT ON COLUMN stg_indicadores_demograficos.muj_60_mas IS 'Población femenina de 60 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.hom_60_mas IS 'Población masculina de 60 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_60_mas IS 'Población total de 60 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.muj_65_mas IS 'Población femenina de 65 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.hom_65_mas IS 'Población masculina de 65 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_65_mas IS 'Población total de 65 años y más.';
COMMENT ON COLUMN stg_indicadores_demograficos.pob_mit_ent IS 'Población total de la entidad (Jalisco) a mitad de año.';
COMMENT ON COLUMN stg_indicadores_demograficos.edad_med IS 'Edad mediana de la población del municipio.';
COMMENT ON COLUMN stg_indicadores_demograficos.por_mun IS 'Porcentaje de la población del municipio respecto a la entidad.';
COMMENT ON COLUMN stg_indicadores_demograficos.ind_env_60 IS 'Índice de envejecimiento (población 60+ / población 0-14 * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.ind_env_65 IS 'Índice de envejecimiento (población 65+ / población 0-14 * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.rhm IS 'Razón de hombres masculinos (hombres / mujeres * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.raz_dep_adu IS 'Razón de dependencia adulta (población 60+ / población 15-59 * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.raz_dep_inf IS 'Razón de dependencia infantil (población 0-14 / población 15-64 * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.raz_dep IS 'Razón de dependencia total (población 0-14 + 60+ / población 15-59 * 100).';
COMMENT ON COLUMN stg_indicadores_demograficos.fecha_actualizacion IS 'Fecha de actualización del registro.';

COMMENT ON VIEW view_poblacion_mitad_anio IS 'Vista de integración que desnormaliza stg_poblacion_mitad_anio con nombres de municipio, entidad y sexo. Filtra solo datos de Jalisco (cve_ent = 14).';
COMMENT ON VIEW view_grandes_grupos_edad IS 'Vista de integración que desnormaliza stg_grandes_grupos_edad con nombres de municipio, entidad y sexo. Filtra solo datos de Jalisco (cve_ent = 14).';
COMMENT ON VIEW view_indicadores_demograficos IS 'Vista de integración que desnormaliza stg_indicadores_demograficos con nombres de municipio y entidad. Filtra solo datos de Jalisco (cve_ent = 14).';
