CREATE TABLE IF NOT EXISTS centros (
    clave_centro_trabajo VARCHAR(20) PRIMARY KEY,
    nombre_centro_trabajo TEXT NOT NULL,
    turno_id INTEGER REFERENCES turnos(id),
    tipos_educativos_id INTEGER REFERENCES tipos_educativos(id),
    nivel_educativo_id INTEGER REFERENCES niveles_educativos(id),
    servicio_educativo_id INTEGER REFERENCES servicios_educativos(id),
    tipo_control_id INTEGER REFERENCES tipos_controles(id),
    tipo_sostenimiento_id INTEGER REFERENCES tipos_sostenimiento(id),
    entidad_id INTEGER,
    municipio_id INTEGER,
    localidades_id INTEGER REFERENCES localidades(id),
    domicilios_id INTEGER REFERENCES domicilios(id),
    colonias_id INTEGER REFERENCES colonias(id),
    total_alumnos_hombres INTEGER,
    total_alumnas_mujeres INTEGER,
    total_docentes_hombres INTEGER,
    total_docentes_mujeres INTEGER,
    aulas_en_uso INTEGER,
    aulas_existentes INTEGER,
    latitud FLOAT,
    longitud FLOAT,
    fecha_actualizacion DATE NOT NULL
);