-- Tabla de hechos.

CREATE TABLE IF NOT EXISTS stg_defunciones (
	id SERIAL NOT NULL,
	entidad_registro INTEGER,
	municipio_regis INTEGER,
	tamanio_loc_regis_id INTEGER,
	localidad_regis INTEGER,
	entidad_resid INTEGER,
	municipio_resid INTEGER,
	tamanio_loc_resid_id INTEGER,
	localidad_resid INTEGER,
	entidad_ocurr INTEGER,
	municipio_ocurr INTEGER,
	tamanio_loc_ocurr_id INTEGER,
	localidad_ocurr INTEGER,
	causa_defuncion_id INTEGER,
	cod_adicional_id INTEGER,
	lista_mex_id INTEGER,
	sexo_id INTEGER,
	entidad_nac INTEGER,
	afromex_id INTEGER,
	cond_indigena_id INTEGER,
	lengua_indigena_id INTEGER,
	lenguas_id INTEGER,
	nacionalid_id INTEGER,
	origen_id INTEGER,
	edad_id INTEGER,
	edad_gestacional_id INTEGER,
	gramos_id INTEGER,
	dia_ocurr_id INTEGER,
	mes_ocurr_id INTEGER,
	anio_ocurr_id INTEGER,
	dia_registro_id INTEGER,
	mes_registro_id INTEGER,
	anio_registro_id INTEGER,
	dia_nacimiento_id INTEGER,
	mes_nacimiento_id INTEGER,
	anio_nacimiento_id INTEGER,
	condicion_act_id INTEGER,
	ocupacion_id INTEGER,
	escolaridad_id INTEGER,
	edo_civil_id INTEGER,
	tipo_defuncion_id INTEGER,
	ocurr_trab_id INTEGER,
	lugar_ocurr_id INTEGER,
	parentesco_agre_id INTEGER,
	violencia_familiar_id INTEGER,
	asist_medica_id INTEGER,
	cirugia_id INTEGER,
	accidental_vio_id INTEGER,
	necropsia_id INTEGER,
	uso_necropsia_id INTEGER,
	encefalica_id INTEGER,
	donador_id INTEGER,
	sitio_ocur_id INTEGER,
	certificante_id INTEGER,
	derecho_hab_id INTEGER,
	embarazo_id INTEGER,
	rel_emba_id INTEGER,
	horas_id INTEGER,
	minutos_id INTEGER,
	capitulo INTEGER,
	grupo INTEGER,
	capitulo_grupo_id INTEGER,
	lista_cie_id INTEGER,
	gr_lismex_id INTEGER,
	area_urbana_id INTEGER,
	edad_agrupada_id INTEGER,
	complicaron_id INTEGER,
	dia_certificacion_id INTEGER,
	mes_certificacion_id INTEGER,
	anio_certificacion_id INTEGER,
	maternas_id INTEGER,
	entidad_ocules INTEGER,
	municipio_ocules INTEGER,
	localidad_ocules INTEGER,
	razon_m_id INTEGER,
	dis_re_oax INTEGER,
	municipio_resid_id INTEGER,
	municipio_ocurr_id INTEGER,
	edicion_id INTEGER,
	fecha_actualizacion DATE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(tamanio_loc_regis_id) REFERENCES cat_tamano_localidad (id),
	FOREIGN KEY(tamanio_loc_resid_id) REFERENCES cat_tamano_localidad (id),
	FOREIGN KEY(tamanio_loc_ocurr_id) REFERENCES cat_tamano_localidad (id),
	FOREIGN KEY(causa_defuncion_id) REFERENCES cat_causa_defuncion (id),
	FOREIGN KEY(cod_adicional_id) REFERENCES cat_codigo_adicional (id),
	FOREIGN KEY(lista_mex_id) REFERENCES cat_lista_mexicana (id),
	FOREIGN KEY(sexo_id) REFERENCES cat_sexo (id),
	FOREIGN KEY(afromex_id) REFERENCES cat_afromexicano (id),
	FOREIGN KEY(cond_indigena_id) REFERENCES cat_condicion_indigena (id),
	FOREIGN KEY(lengua_indigena_id) REFERENCES cat_lengua_indigena (id),
	FOREIGN KEY(lenguas_id) REFERENCES cat_lenguas (id),
	FOREIGN KEY(nacionalid_id) REFERENCES cat_nacionalidad (id),
	FOREIGN KEY(origen_id) REFERENCES cat_origen (id),
	FOREIGN KEY(edad_id) REFERENCES cat_edad (id),
	FOREIGN KEY(edad_gestacional_id) REFERENCES cat_edad_gestacional (id),
	FOREIGN KEY(gramos_id) REFERENCES cat_peso_producto (id),
	FOREIGN KEY(dia_ocurr_id) REFERENCES cat_dia (id),
	FOREIGN KEY(mes_ocurr_id) REFERENCES cat_mes (id),
	FOREIGN KEY(anio_ocurr_id) REFERENCES cat_anio (id),
	FOREIGN KEY(dia_registro_id) REFERENCES cat_dia (id),
	FOREIGN KEY(mes_registro_id) REFERENCES cat_mes (id),
	FOREIGN KEY(anio_registro_id) REFERENCES cat_anio (id),
	FOREIGN KEY(dia_nacimiento_id) REFERENCES cat_dia (id),
	FOREIGN KEY(mes_nacimiento_id) REFERENCES cat_mes (id),
	FOREIGN KEY(anio_nacimiento_id) REFERENCES cat_anio (id),
	FOREIGN KEY(condicion_act_id) REFERENCES cat_condicion_actividad (id),
	FOREIGN KEY(ocupacion_id) REFERENCES cat_ocupacion (id),
	FOREIGN KEY(escolaridad_id) REFERENCES cat_escolaridad (id),
	FOREIGN KEY(edo_civil_id) REFERENCES cat_estado_civil (id),
	FOREIGN KEY(tipo_defuncion_id) REFERENCES cat_presunta_defuncion_violenta (id),
	FOREIGN KEY(ocurr_trab_id) REFERENCES cat_ocurrio_trabajo (id),
	FOREIGN KEY(lugar_ocurr_id) REFERENCES cat_lugar_ocurrencia (id),
	FOREIGN KEY(parentesco_agre_id) REFERENCES cat_parentesco_agresor (id),
	FOREIGN KEY(violencia_familiar_id) REFERENCES cat_violencia_familiar (id),
	FOREIGN KEY(asist_medica_id) REFERENCES cat_asistencia_medica (id),
	FOREIGN KEY(cirugia_id) REFERENCES cat_cirugia (id),
	FOREIGN KEY(accidental_vio_id) REFERENCES cat_accidental_violenta (id),
	FOREIGN KEY(necropsia_id) REFERENCES cat_necropsia (id),
	FOREIGN KEY(uso_necropsia_id) REFERENCES cat_uso_necropsia (id),
	FOREIGN KEY(encefalica_id) REFERENCES cat_muerte_encefalica (id),
	FOREIGN KEY(donador_id) REFERENCES cat_donador (id),
	FOREIGN KEY(sitio_ocur_id) REFERENCES cat_sitio_ocurrencia (id),
	FOREIGN KEY(certificante_id) REFERENCES cat_certificante (id),
	FOREIGN KEY(derecho_hab_id) REFERENCES cat_derecho_habiencia (id),
	FOREIGN KEY(embarazo_id) REFERENCES cat_condicion_embarazo (id),
	FOREIGN KEY(rel_emba_id) REFERENCES cat_relacion_con_embarazo (id),
	FOREIGN KEY(horas_id) REFERENCES cat_hora (id),
	FOREIGN KEY(minutos_id) REFERENCES cat_minuto (id),
	FOREIGN KEY(capitulo_grupo_id) REFERENCES cat_capitulo_grupo (id),
	FOREIGN KEY(lista_cie_id) REFERENCES cat_lista_cie (id),
	FOREIGN KEY(gr_lismex_id) REFERENCES cat_grupo_lista_mexicana (id),
	FOREIGN KEY(area_urbana_id) REFERENCES cat_area_urbana_rural (id),
	FOREIGN KEY(edad_agrupada_id) REFERENCES cat_edad_agrupada (id),
	FOREIGN KEY(complicaron_id) REFERENCES cat_complicaron_embarazo (id),
	FOREIGN KEY(dia_certificacion_id) REFERENCES cat_dia (id),
	FOREIGN KEY(mes_certificacion_id) REFERENCES cat_mes (id),
	FOREIGN KEY(anio_certificacion_id) REFERENCES cat_anio (id),
	FOREIGN KEY(maternas_id) REFERENCES cat_causa_defuncion (id),
	FOREIGN KEY(razon_m_id) REFERENCES cat_razon_materna (id),
	FOREIGN KEY(edicion_id) REFERENCES cat_edicion (id)
);
