-- Comentarios de tablas y columnas del pipeline defunciones.

-- Catálogos simples
COMMENT ON TABLE cat_edad IS 'Catálogo de edad (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_edad.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_edad.nombre_edad IS 'Descripción de edad.';
COMMENT ON TABLE cat_sexo IS 'Catálogo de sexo (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_sexo.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_sexo.descripcion IS 'Descripción de sexo.';
COMMENT ON TABLE cat_asistencia_medica IS 'Catálogo de asistencia medica (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_asistencia_medica.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_asistencia_medica.descripcion IS 'Descripción de asistencia medica.';
COMMENT ON TABLE cat_escolaridad IS 'Catálogo de escolaridad (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_escolaridad.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_escolaridad.descripcion IS 'Descripción de escolaridad.';
COMMENT ON TABLE cat_estado_civil IS 'Catálogo de estado civil (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_estado_civil.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_estado_civil.descripcion IS 'Descripción de estado civil.';
COMMENT ON TABLE cat_nacionalidad IS 'Catálogo de nacionalidad (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_nacionalidad.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_nacionalidad.descripcion IS 'Descripción de nacionalidad.';
COMMENT ON TABLE cat_condicion_actividad IS 'Catálogo de condicion actividad (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_condicion_actividad.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_condicion_actividad.descripcion IS 'Descripción de condicion actividad.';
COMMENT ON TABLE cat_afromexicano IS 'Catálogo de afromexicano (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_afromexicano.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_afromexicano.descripcion IS 'Descripción de afromexicano.';
COMMENT ON TABLE cat_condicion_indigena IS 'Catálogo de condicion indigena (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_condicion_indigena.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_condicion_indigena.descripcion IS 'Descripción de condicion indigena.';
COMMENT ON TABLE cat_lengua_indigena IS 'Catálogo de lengua indigena (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_lengua_indigena.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_lengua_indigena.descripcion IS 'Descripción de lengua indigena.';
COMMENT ON TABLE cat_lenguas IS 'Catálogo de lenguas (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_lenguas.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_lenguas.descripcion IS 'Descripción de lenguas.';
COMMENT ON TABLE cat_edad_agrupada IS 'Catálogo de edad agrupada (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_edad_agrupada.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_edad_agrupada.descripcion IS 'Descripción de edad agrupada.';
COMMENT ON TABLE cat_edad_gestacional IS 'Catálogo de edad gestacional (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_edad_gestacional.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_edad_gestacional.descripcion IS 'Descripción de edad gestacional.';
COMMENT ON TABLE cat_origen IS 'Catálogo de origen (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_origen.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_origen.descripcion IS 'Descripción de origen.';
COMMENT ON TABLE cat_lista_cie IS 'Catálogo de lista cie (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_lista_cie.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_lista_cie.descripcion IS 'Descripción de lista cie.';
COMMENT ON TABLE cat_lugar_ocurrencia IS 'Catálogo de lugar ocurrencia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_lugar_ocurrencia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_lugar_ocurrencia.descripcion IS 'Descripción de lugar ocurrencia.';
COMMENT ON TABLE cat_sitio_ocurrencia IS 'Catálogo de sitio ocurrencia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_sitio_ocurrencia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_sitio_ocurrencia.descripcion IS 'Descripción de sitio ocurrencia.';
COMMENT ON TABLE cat_necropsia IS 'Catálogo de necropsia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_necropsia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_necropsia.descripcion IS 'Descripción de necropsia.';
COMMENT ON TABLE cat_uso_necropsia IS 'Catálogo de uso necropsia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_uso_necropsia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_uso_necropsia.descripcion IS 'Descripción de uso necropsia.';
COMMENT ON TABLE cat_certificante IS 'Catálogo de certificante (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_certificante.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_certificante.descripcion IS 'Descripción de certificante.';
COMMENT ON TABLE cat_ocurrio_trabajo IS 'Catálogo de ocurrio trabajo (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_ocurrio_trabajo.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_ocurrio_trabajo.descripcion IS 'Descripción de ocurrio trabajo.';
COMMENT ON TABLE cat_accidental_violenta IS 'Catálogo de accidental violenta (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_accidental_violenta.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_accidental_violenta.descripcion IS 'Descripción de accidental violenta.';
COMMENT ON TABLE cat_cirugia IS 'Catálogo de cirugia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_cirugia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_cirugia.descripcion IS 'Descripción de cirugia.';
COMMENT ON TABLE cat_muerte_encefalica IS 'Catálogo de muerte encefalica (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_muerte_encefalica.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_muerte_encefalica.descripcion IS 'Descripción de muerte encefalica.';
COMMENT ON TABLE cat_donador IS 'Catálogo de donador (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_donador.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_donador.descripcion IS 'Descripción de donador.';
COMMENT ON TABLE cat_area_urbana_rural IS 'Catálogo de area urbana rural (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_area_urbana_rural.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_area_urbana_rural.descripcion IS 'Descripción de area urbana rural.';
COMMENT ON TABLE cat_tamano_localidad IS 'Catálogo de tamano localidad (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_tamano_localidad.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_tamano_localidad.descripcion IS 'Descripción de tamano localidad.';
COMMENT ON TABLE cat_condicion_embarazo IS 'Catálogo de condicion embarazo (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_condicion_embarazo.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_condicion_embarazo.descripcion IS 'Descripción de condicion embarazo.';
COMMENT ON TABLE cat_relacion_con_embarazo IS 'Catálogo de relacion con embarazo (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_relacion_con_embarazo.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_relacion_con_embarazo.descripcion IS 'Descripción de relacion con embarazo.';
COMMENT ON TABLE cat_complicaron_embarazo IS 'Catálogo de complicaron embarazo (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_complicaron_embarazo.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_complicaron_embarazo.descripcion IS 'Descripción de complicaron embarazo.';
COMMENT ON TABLE cat_violencia_familiar IS 'Catálogo de violencia familiar (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_violencia_familiar.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_violencia_familiar.descripcion IS 'Descripción de violencia familiar.';
COMMENT ON TABLE cat_parentesco_agresor IS 'Catálogo de parentesco agresor (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_parentesco_agresor.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_parentesco_agresor.descripcion IS 'Descripción de parentesco agresor.';
COMMENT ON TABLE cat_dia IS 'Catálogo de dia (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_dia.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_dia.descripcion IS 'Descripción de dia.';
COMMENT ON TABLE cat_mes IS 'Catálogo de mes (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_mes.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_mes.descripcion IS 'Descripción de mes.';
COMMENT ON TABLE cat_anio IS 'Catálogo de anio (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_anio.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_anio.descripcion IS 'Descripción de anio.';
COMMENT ON TABLE cat_hora IS 'Catálogo de hora (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_hora.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_hora.descripcion IS 'Descripción de hora.';
COMMENT ON TABLE cat_minuto IS 'Catálogo de minuto (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_minuto.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_minuto.descripcion IS 'Descripción de minuto.';
COMMENT ON TABLE cat_razon_materna IS 'Catálogo de razon materna (fuente: DGIS defunciones).';
COMMENT ON COLUMN cat_razon_materna.id IS 'Clave del catálogo (código oficial DGIS).';
COMMENT ON COLUMN cat_razon_materna.descripcion IS 'Descripción de razon materna.';
-- Catálogos codificados (id surrogate + codigo alfanumérico)
COMMENT ON TABLE cat_causa_defuncion IS 'Catálogo de causa defuncion (código alfanumérico CIE con id surrogate).';
COMMENT ON COLUMN cat_causa_defuncion.id IS 'Id surrogate generado.';
COMMENT ON COLUMN cat_causa_defuncion.codigo IS 'Código oficial DGIS (alfanumérico).';
COMMENT ON COLUMN cat_causa_defuncion.descripcion IS 'Descripción de causa defuncion.';
COMMENT ON TABLE cat_codigo_adicional IS 'Catálogo de codigo adicional (código alfanumérico CIE con id surrogate).';
COMMENT ON COLUMN cat_codigo_adicional.id IS 'Id surrogate generado.';
COMMENT ON COLUMN cat_codigo_adicional.codigo IS 'Código oficial DGIS (alfanumérico).';
COMMENT ON COLUMN cat_codigo_adicional.descripcion IS 'Descripción de codigo adicional.';
COMMENT ON TABLE cat_lista_mexicana IS 'Catálogo de lista mexicana (código alfanumérico CIE con id surrogate).';
COMMENT ON COLUMN cat_lista_mexicana.id IS 'Id surrogate generado.';
COMMENT ON COLUMN cat_lista_mexicana.codigo IS 'Código oficial DGIS (alfanumérico).';
COMMENT ON COLUMN cat_lista_mexicana.descripcion IS 'Descripción de lista mexicana.';
COMMENT ON TABLE cat_grupo_lista_mexicana IS 'Catálogo de grupo lista mexicana (código alfanumérico CIE con id surrogate).';
COMMENT ON COLUMN cat_grupo_lista_mexicana.id IS 'Id surrogate generado.';
COMMENT ON COLUMN cat_grupo_lista_mexicana.codigo IS 'Código oficial DGIS (alfanumérico).';
COMMENT ON COLUMN cat_grupo_lista_mexicana.descripcion IS 'Descripción de grupo lista mexicana.';
COMMENT ON TABLE cat_peso_producto IS 'Catálogo de peso producto (código alfanumérico CIE con id surrogate).';
COMMENT ON COLUMN cat_peso_producto.id IS 'Id surrogate generado.';
COMMENT ON COLUMN cat_peso_producto.codigo IS 'Código oficial DGIS (alfanumérico).';
COMMENT ON COLUMN cat_peso_producto.descripcion IS 'Descripción de peso producto.';
COMMENT ON TABLE cat_capitulo_grupo IS 'Clasificación CIE-10 capítulo/grupo (id surrogate sobre cap+gpo).';
COMMENT ON COLUMN cat_capitulo_grupo.cap IS 'Capítulo CIE-10.';
COMMENT ON COLUMN cat_capitulo_grupo.gpo IS 'Grupo (0 = capítulo completo).';
COMMENT ON TABLE cat_edicion IS 'Dimensión de edición (año de publicación DGIS).';
COMMENT ON COLUMN cat_edicion.anio IS 'Año de la edición.';
COMMENT ON TABLE cat_ocupacion IS 'Catálogo versionado por edición de ocupacion (códigos cambian de significado entre años).';
COMMENT ON COLUMN cat_ocupacion.codigo IS 'Código DGIS de la edición.';
COMMENT ON COLUMN cat_ocupacion.edicion_id IS 'Edición a la que aplica.';
COMMENT ON TABLE cat_derecho_habiencia IS 'Catálogo versionado por edición de derecho habiencia (códigos cambian de significado entre años).';
COMMENT ON COLUMN cat_derecho_habiencia.codigo IS 'Código DGIS de la edición.';
COMMENT ON COLUMN cat_derecho_habiencia.edicion_id IS 'Edición a la que aplica.';
COMMENT ON TABLE cat_presunta_defuncion_violenta IS 'Catálogo versionado por edición de presunta defuncion violenta (códigos cambian de significado entre años).';
COMMENT ON COLUMN cat_presunta_defuncion_violenta.codigo IS 'Código DGIS de la edición.';
COMMENT ON COLUMN cat_presunta_defuncion_violenta.edicion_id IS 'Edición a la que aplica.';

-- Tabla de hechos
COMMENT ON TABLE stg_defunciones IS 'Registro de defunciones (DGIS), filtrado a residentes de Jalisco.';
COMMENT ON COLUMN stg_defunciones.id IS 'Identificador único de la fila.';
COMMENT ON COLUMN stg_defunciones.entidad_registro IS 'Entidad de registro';
COMMENT ON COLUMN stg_defunciones.municipio_regis IS 'Municipio o demarcación territorial de registro';
COMMENT ON COLUMN stg_defunciones.tamanio_loc_regis_id IS 'Tamaño de localidad de registro';
COMMENT ON COLUMN stg_defunciones.localidad_regis IS 'Localidad de registro';
COMMENT ON COLUMN stg_defunciones.entidad_resid IS 'Entidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.municipio_resid IS 'Municipio o demarcación territorial de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.tamanio_loc_resid_id IS 'Tamaño de localidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.localidad_resid IS 'Localidad de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.entidad_ocurr IS 'Entidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.municipio_ocurr IS 'Municipio o demarcación territorial de ocurrencia';
COMMENT ON COLUMN stg_defunciones.tamanio_loc_ocurr_id IS 'Tamaño de localidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.localidad_ocurr IS 'Localidad de ocurrencia';
COMMENT ON COLUMN stg_defunciones.causa_defuncion_id IS 'Causa de la defunción (lista detallada)';
COMMENT ON COLUMN stg_defunciones.cod_adicional_id IS 'Código adicional CIE';
COMMENT ON COLUMN stg_defunciones.lista_mex_id IS 'Causa de la defunción (lista mexicana)';
COMMENT ON COLUMN stg_defunciones.sexo_id IS 'Sexo del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.entidad_nac IS 'Lugar de nacimiento';
COMMENT ON COLUMN stg_defunciones.afromex_id IS 'Condición de autoadscripción como persona afromexicana';
COMMENT ON COLUMN stg_defunciones.cond_indigena_id IS 'Condición de autoadscripción como persona indígena';
COMMENT ON COLUMN stg_defunciones.lengua_indigena_id IS 'Condición de habla lengua indígena del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.lenguas_id IS 'Clave de la lengua indígena';
COMMENT ON COLUMN stg_defunciones.nacionalid_id IS 'Nacionalidad del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.origen_id IS 'Origen específico (estado si mexicano, país si extranjero).';
COMMENT ON COLUMN stg_defunciones.edad_id IS 'Edad del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.edad_gestacional_id IS 'Semanas de gestación de las personas fallecidas';
COMMENT ON COLUMN stg_defunciones.gramos_id IS 'Peso en gramos de las personas fallecidas con menos de 28 días de edad';
COMMENT ON COLUMN stg_defunciones.dia_ocurr_id IS 'Día de ocurrencia';
COMMENT ON COLUMN stg_defunciones.mes_ocurr_id IS 'Mes de ocurrencia';
COMMENT ON COLUMN stg_defunciones.anio_ocurr_id IS 'Año de ocurrencia';
COMMENT ON COLUMN stg_defunciones.dia_registro_id IS 'Día de registro';
COMMENT ON COLUMN stg_defunciones.mes_registro_id IS 'Mes de registro';
COMMENT ON COLUMN stg_defunciones.anio_registro_id IS 'Año de registro';
COMMENT ON COLUMN stg_defunciones.dia_nacimiento_id IS 'Día de nacimiento del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.mes_nacimiento_id IS 'Mes de nacimiento del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.anio_nacimiento_id IS 'Año de nacimiento del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.condicion_act_id IS 'Condición de actividad económica del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.ocupacion_id IS 'Ocupación del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.escolaridad_id IS 'Nivel de escolaridad del (la) fallecido (a) (escolaridad)';
COMMENT ON COLUMN stg_defunciones.edo_civil_id IS 'Estado conyugal (civil) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.tipo_defuncion_id IS 'Tipo de defunción (presunto)';
COMMENT ON COLUMN stg_defunciones.ocurr_trab_id IS 'Ocurrió en el desempeño de su trabajo';
COMMENT ON COLUMN stg_defunciones.lugar_ocurr_id IS 'Sitio de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.parentesco_agre_id IS 'Parentesco del presunto agresor';
COMMENT ON COLUMN stg_defunciones.violencia_familiar_id IS 'Violencia familiar';
COMMENT ON COLUMN stg_defunciones.asist_medica_id IS 'Condición de atención médica';
COMMENT ON COLUMN stg_defunciones.cirugia_id IS 'Condición de cirugía';
COMMENT ON COLUMN stg_defunciones.accidental_vio_id IS 'La muerte fue accidental o violenta';
COMMENT ON COLUMN stg_defunciones.necropsia_id IS 'Condición de necropsia';
COMMENT ON COLUMN stg_defunciones.uso_necropsia_id IS 'Condición de uso de la necropsia';
COMMENT ON COLUMN stg_defunciones.encefalica_id IS 'Condición de muerte encefálica';
COMMENT ON COLUMN stg_defunciones.donador_id IS 'Condición de donador(a) de órganos';
COMMENT ON COLUMN stg_defunciones.sitio_ocur_id IS 'Sitio de ocurrencia de la defunción';
COMMENT ON COLUMN stg_defunciones.certificante_id IS 'Persona que certificó la defunción';
COMMENT ON COLUMN stg_defunciones.derecho_hab_id IS 'Afiliación a los servicios de salud (derechohabiencia) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.embarazo_id IS 'Condición de embarazo';
COMMENT ON COLUMN stg_defunciones.rel_emba_id IS 'Causas relacionadas con el embarazo';
COMMENT ON COLUMN stg_defunciones.horas_id IS 'Hora de la defunción';
COMMENT ON COLUMN stg_defunciones.minutos_id IS 'Minuto de la defunción';
COMMENT ON COLUMN stg_defunciones.capitulo IS 'Causas detalladas CIE (capítulo)';
COMMENT ON COLUMN stg_defunciones.grupo IS 'Causas detalladas CIE (grupo)';
COMMENT ON COLUMN stg_defunciones.capitulo_grupo_id IS 'Clasificación CIE-10 capítulo/grupo.';
COMMENT ON COLUMN stg_defunciones.lista_cie_id IS 'Lista de tabulación 1 para mortalidad de la CIE';
COMMENT ON COLUMN stg_defunciones.gr_lismex_id IS 'Lista mexicana de enfermedades (grupo)';
COMMENT ON COLUMN stg_defunciones.area_urbana_id IS 'Área urbana-rural de residencia habitual del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.edad_agrupada_id IS 'Edad (agrupada) del (la) fallecido (a)';
COMMENT ON COLUMN stg_defunciones.complicaron_id IS 'Complicaron el embarazo';
COMMENT ON COLUMN stg_defunciones.dia_certificacion_id IS 'Día de certificación';
COMMENT ON COLUMN stg_defunciones.mes_certificacion_id IS 'Mes de certificación';
COMMENT ON COLUMN stg_defunciones.anio_certificacion_id IS 'Año de certificación';
COMMENT ON COLUMN stg_defunciones.maternas_id IS 'Defunciones maternas totales';
COMMENT ON COLUMN stg_defunciones.entidad_ocules IS 'Entidad de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.municipio_ocules IS 'Municipio o demarcación territorial de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.localidad_ocules IS 'Localidad de ocurrencia de la lesión';
COMMENT ON COLUMN stg_defunciones.razon_m_id IS 'Defunciones para calcular la razón de la mortalidad materna';
COMMENT ON COLUMN stg_defunciones.dis_re_oax IS 'Distritos de registro de Oaxaca';
COMMENT ON COLUMN stg_defunciones.municipio_resid_id IS 'Municipio de residencia (cvegeo).';
COMMENT ON COLUMN stg_defunciones.municipio_ocurr_id IS 'Municipio de ocurrencia (cvegeo).';
COMMENT ON COLUMN stg_defunciones.edicion_id IS 'Edición DGIS de origen.';
COMMENT ON COLUMN stg_defunciones.fecha_actualizacion IS 'Fecha de carga ETL.';
