from enum import StrEnum, auto


class DefuncionesTables(StrEnum):
    CAT_EDAD = auto()
    CAT_ASISTENCIA_MEDICA = auto()
    CAT_SEXO = auto()

    CAT_ESCOLARIDAD = auto()
    CAT_ESTADO_CIVIL = auto()
    CAT_DERECHO_HABIENCIA = auto()
    CAT_NACIONALIDAD = auto()
    CAT_ENTIDAD_PAIS = auto()
    CAT_LOCALIDADES = auto()
    CAT_CONDICION_ACTIVIDAD = auto()
    CAT_OCUPACION = auto()
    CAT_AFROMEXICANO = auto()
    CAT_CONDICION_INDIGENA = auto()
    CAT_LENGUA_INDIGENA = auto()
    CAT_LENGUAS = auto()
    CAT_EDAD_AGRUPADA = auto()
    CAT_EDAD_GESTACIONAL = auto()
    CAT_ORIGEN = auto()
    CAT_CAUSA_DEFUNCION = auto()
    CAT_CODIGO_ADICIONAL = auto()
    CAT_LISTA_MEXICANA = auto()
    CAT_GRUPO_LISTA_MEXICANA = auto()
    CAT_LISTA_CIE = auto()
    CAT_LUGAR_OCURRENCIA = auto()
    CAT_SITIO_OCURRENCIA = auto()
    CAT_NECROPSIA = auto()
    CAT_USO_NECROPSIA = auto()
    CAT_CERTIFICANTE = auto()
    CAT_OCURRIO_TRABAJO = auto()
    CAT_ACCIDENTAL_VIOLENTA = auto()
    CAT_PRESUNTA_DEFUNCION_VIOLENTA = auto()
    CAT_CIRUGIA = auto()
    CAT_MUERTE_ENCEFALICA = auto()
    CAT_DONADOR = auto()
    CAT_AREA_URBANA_RURAL = auto()
    CAT_TAMANO_LOCALIDAD = auto()
    CAT_CONDICION_EMBARAZO = auto()
    CAT_RELACION_CON_EMBARAZO = auto()
    CAT_COMPLICARON_EMBARAZO = auto()
    CAT_RAZON_MATERNA = auto()
    CAT_PESO_PRODUCTO = auto()
    CAT_VIOLENCIA_FAMILIAR = auto()
    CAT_PARENTESCO_AGRESOR = auto()
    CAT_DIA = auto()
    CAT_MES = auto()
    CAT_ANIO = auto()
    CAT_HORA = auto()
    CAT_MINUTO = auto()

    CAT_CAPITULO_GRUPO = auto()

    CAT_EDICION = auto()

    STG_DEFUNCIONES = auto()
