name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  pre-commit:
    name: Pre-commit hooks
    uses: ./.github/workflows/pre-commit.yml

  build:
    name: Docker build & DAGs
    needs: pre-commit
    uses: ./.github/workflows/docker-build.yml
